import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
import fc from "fast-check";
import { MlsRelayMessage, RelayClientMessage, RelayServerMessage, maxRoomNameChars } from "../src/index.js";
import { buildGoldenFixtureDocument, goldenSchemas, renderGoldenFixtureFile } from "./golden-fixtures.js";

const fixturePath = resolve(import.meta.dirname, "../fixtures/golden-v1.json");

test("checked-in golden fixtures are generated by and round-trip through the TypeScript authority", () => {
  assert.equal(readFileSync(fixturePath, "utf8"), renderGoldenFixtureFile());
  for (const fixture of buildGoldenFixtureDocument().cases) {
    const decoded = JSON.parse(fixture.json) as unknown;
    const parsed = goldenSchemas[fixture.schema].parse(decoded);
    assert.equal(JSON.stringify(parsed), fixture.json, fixture.name);
  }
});

test("unknown-field behavior distinguishes strict MLS records from stripping relay records", () => {
  const fixtures = buildGoldenFixtureDocument().cases;
  const application = JSON.parse(fixtures.find(({ name }) => name === "mls-application")!.json);
  assert.equal(MlsRelayMessage.safeParse({ ...application, unknown: true }).success, false);

  const inviteResponse = JSON.parse(fixtures.find(({ name }) => name === "invite-response")!.json);
  assert.equal(
    goldenSchemas.InviteResponseRecord.safeParse({
      ...inviteResponse,
      responseBinding: { ...inviteResponse.responseBinding, unknown: true }
    }).success,
    false
  );

  const join = {
    type: "join",
    teamId: "team-1",
    roomId: "room-1",
    userId: "user-1",
    deviceId: "device-1",
    unknown: true
  };
  assert.deepEqual(RelayClientMessage.parse(join), {
    type: "join",
    teamId: "team-1",
    roomId: "room-1",
    userId: "user-1",
    deviceId: "device-1"
  });
  assert.equal(RelayServerMessage.safeParse({ type: "future.record" }).success, false);
});

test("boundary, malformed, oversized, and unsupported relay inputs match the authority", () => {
  const room = {
    id: "room-1",
    teamId: "team-1",
    name: "r".repeat(maxRoomNameChars),
    host: "Host",
    hostUserId: "user-1",
    hostStatus: "active",
    approvalPolicy: "ask_every_turn"
  };
  assert.equal(goldenSchemas.RoomRecord.safeParse(room).success, true);
  assert.equal(goldenSchemas.RoomRecord.safeParse({ ...room, name: `${room.name}r` }).success, false);
  assert.equal(RelayClientMessage.safeParse({ type: "join" }).success, false);
  assert.equal(RelayClientMessage.safeParse({ type: "future.record" }).success, false);
  assert.equal(RelayServerMessage.safeParse(null).success, false);
  assert.equal(goldenSchemas.RoomRecord.safeParse({ ...room, archivedAt: "2026-07-18T12:34:56+00:00" }).success, false);
  assert.equal(goldenSchemas.RoomRecord.safeParse({ ...room, archivedAt: null }).success, false);
  assert.equal(goldenSchemas.RoomRecord.safeParse({ ...room, unknown: null }).success, true);
  assert.equal(goldenSchemas.RoomRecord.safeParse({ ...room, acceptedMlsEpoch: 1.0 }).success, true);

  const terminalResult = {
    eventType: "terminal.result",
    requestId: "request-1",
    command: "true",
    cwd: "/tmp/project",
    exitStatus: null,
    stdout: "",
    stderr: "",
    ranBy: "Maddie",
    ranByUserId: "user-1",
    startedAt: "2026-07-18T12:34:56.000Z",
    finishedAt: "2026-07-18T12:34:56.000Z"
  };
  assert.equal(goldenSchemas.TerminalResultPlaintextPayload.safeParse(terminalResult).success, true);
  const missingExitStatus = { ...terminalResult } as Partial<typeof terminalResult>;
  delete missingExitStatus.exitStatus;
  assert.equal(goldenSchemas.TerminalResultPlaintextPayload.safeParse(missingExitStatus).success, false);

  const fixtures = buildGoldenFixtureDocument().cases;
  const handoff = JSON.parse(fixtures.find(({ name }) => name === "mls-host-handoff")!.json);
  handoff.hostTransferAuthorization.version = 3;
  assert.equal(MlsRelayMessage.safeParse(handoff).success, false);
  const inviteResponse = JSON.parse(fixtures.find(({ name }) => name === "invite-response")!.json);
  inviteResponse.responseBinding.version = 4;
  assert.equal(goldenSchemas.InviteResponseRecord.safeParse(inviteResponse).success, false);
});

test("property-generated unknown fields are stripped from non-strict top-level relay variants", () => {
  fc.assert(
    fc.property(fc.stringMatching(/^unknown_[a-z0-9]{1,16}$/), fc.jsonValue(), (key, value) => {
      const source = { type: "joined", teamId: "team-1", roomId: "room-1", [key]: value };
      const parsed = RelayServerMessage.parse(source);
      assert.equal(Object.hasOwn(parsed, key), false);
    }),
    { numRuns: 500 }
  );
});
