import type {
  LocalPreviewPlaintextPayload
} from "@multaiplayer/protocol";
import {
  codexModelOptions,
  defaultBrowserProfilePersistent,
  defaultCodexModel,
} from "@multaiplayer/protocol";
import { decryptJson } from "@multaiplayer/crypto";
import { loadHistorySettings } from "./lib/localHistory";
import {
  defaultProjectPath,
  type GitWorkflowResult,
} from "./lib/localBackend";
import type { GitHubActionRun } from "./lib/authClient";
import {
  normalizeRoomName
} from "./lib/workspaceCreation";
import { attachmentReviewScopeKey } from "./lib/attachmentPolicy";
import { roomChatGateMessage } from "./lib/chatPolicy";
import type { GitHubActionsTarget } from "./lib/githubWorkflowReadiness";
import type { GitWorkflowDraft } from "./lib/gitWorkflowDraft";
import {
  embeddedAttachmentBytes,
  encodedBytes,
  attachmentTypeFromName,
  formatTimestamp
} from "./lib/appFormatters";
import { useAppStateSlices } from "./hooks/useAppStateSlices";
import { useGitHubAuth } from "./hooks/useGitHubAuth";
import { useLocalIdentity } from "./hooks/useLocalIdentity";
import { useRoomChatMutations } from "./hooks/useRoomChatMutations";
import { useRoomInteractionContext } from "./hooks/useRoomInteractionContext";
import { useRoomScopedSetters } from "./hooks/useRoomScopedSetters";
import { useSelectedRoomRuntime } from "./hooks/useSelectedRoomRuntime";
import { useRoomDisplayContext } from "./hooks/useRoomDisplayContext";
import { useThemeMode } from "./hooks/useThemeMode";
import { useWorkspaceRecordActions } from "./hooks/useWorkspaceRecordActions";
import { useHostHandoffActions } from "./hooks/useHostHandoffActions";
import { useInviteActions } from "./hooks/useInviteActions";
import { useRoomSettingsActor } from "./hooks/useRoomSettingsActor";
import { useAppRefs } from "./hooks/useAppRefs";
import { useAppSelectedContext } from "./hooks/useAppSelectedContext";
import { useAppViewProps } from "./hooks/useAppViewProps";
import { useWorkspaceFlowContext } from "./hooks/useWorkspaceFlowContext";
import { useRelaySyncContext } from "./hooks/useRelaySyncContext";
import { useRoomRuntimeContext } from "./hooks/useRoomRuntimeContext";
import { useRoomPanelActions } from "./hooks/useRoomPanelActions";
import { InlineSecretWarning } from "./components/common";
import { AppShellView } from "./components/AppShellView";
import type { InspectorTab } from "./components/RoomInspectorPanel";
import type {
  BrowserAccessRequest,
  ChatAttachment,
  ChatReaction,
  LocalPreviewRecord,
  NoSecretRoomInvite,
  SidebarPanel,
  TerminalCommandRequest
} from "./types";
import {
  approvalPolicyLabels,
  defaultBrowserReason,
  defaultBrowserStatus,
  defaultBrowserUrl,
  emptyRoom,
  initialMessagesByRoom,
  initialTerminalLinesByRoom,
  maxTerminalActivityLines,
  roomModeLabels,
  seededRooms,
  seededTeamMembers,
  seededTeams
} from "./seedData";

export function App() {
  const { themeMode, toggleThemeMode } = useThemeMode();
  const {
    teams,
    setTeams,
    rooms,
    setRooms,
    teamMembersByTeam,
    setTeamMembersByTeam,
    teamMembersMessageByTeam,
    setTeamMembersMessageByTeam,
    teamMembersBusyByTeam,
    setTeamMembersBusyByTeam,
    workspaceError,
    setWorkspaceError,
    activeSidebarPanel,
    setActiveSidebarPanel,
    newTeamName,
    setNewTeamName,
    newRoomName,
    setNewRoomName,
    newRoomProjectPath,
    setNewRoomProjectPath,
    selectedTeam,
    setSelectedTeam,
    selectedRoomId,
    setSelectedRoomId,
    sidebarQuery,
    setSidebarQuery,
    messagesByRoom,
    setMessagesByRoom,
    appConfig,
    relayHttpDraft,
    relayWsDraft,
    appConfigMessage,
    setRelayHttpDraft,
    setRelayWsDraft,
    saveRelayConfiguration,
    resetRelayConfiguration,
    chatMessagesByRoom,
    setChatMessagesByRoom,
    draftsByRoom,
    setDraftsByRoom,
    pendingAttachmentsByRoom,
    setPendingAttachmentsByRoom,
    sensitiveAttachmentReviewKey,
    setSensitiveAttachmentReviewKey,
    hostBusyByRoom,
    setHostBusyByRoom,
    hostMessagesByRoom,
    setHostMessagesByRoom,
    settingsBusyByRoom,
    setSettingsBusyByRoom,
    settingsMessagesByRoom,
    setSettingsMessagesByRoom,
    customCodexModelsByRoom,
    setCustomCodexModelsByRoom,
    projectPathDraftsByRoom,
    setProjectPathDraftsByRoom,
    historySettings,
    setHistorySettings,
    teamHistorySettings,
    setTeamHistorySettings,
    teamDefaultApprovalPolicy,
    setTeamDefaultApprovalPolicy,
    teamDefaultCodexModel,
    setTeamDefaultCodexModel,
    teamDefaultBrowserProfilePersistent,
    setTeamDefaultBrowserProfilePersistent,
    teamDefaultInviteApprovalGate,
    setTeamDefaultInviteApprovalGate,
    historyMessagesByRoom,
    setHistoryMessagesByRoom,
    teamHistoryMessagesByTeam,
    setTeamHistoryMessagesByTeam,
    inspectorTabsByRoom,
    setInspectorTabsByRoom,
    forgottenRoomIds,
    setForgottenRoomIds,
    revokedRoomIds,
    setRevokedRoomIds,
    revokedTeamIds,
    setRevokedTeamIds,
    presenceByRoom,
    setPresenceByRoom,
    hostHandoffsByRoom,
    setHostHandoffsByRoom,
    codexContinuationByRoom,
    setCodexContinuationByRoom,
    gitWorkflowEventsByRoom,
    setGitWorkflowEventsByRoom,
    githubActionsEventsByRoom,
    setGitHubActionsEventsByRoom,
    codexEventsByRoom,
    setCodexEventsByRoom,
    approvalVisibleByRoom,
    setApprovalVisibleByRoom,
    pendingCodexApprovalsByRoom,
    setPendingCodexApprovalsByRoom,
    codexRunningByRoom,
    setCodexRunningByRoom,
    secretWarningsVisibleByRoom,
    setSecretWarningsVisibleByRoom,
    codexThreadIdsByRoom,
    setCodexThreadIdsByRoom,
    localPreviewsByRoom,
    setLocalPreviewsByRoom,
    localPreviewDialog,
    setLocalPreviewDialog,
    localPreviewBusyByRoom,
    setLocalPreviewBusyByRoom,
    codexProbe,
    setCodexProbe,
    relayStatus,
    setRelayStatus,
    deviceIdentity,
    setDeviceIdentity,
    deviceIdentityMessage,
    setDeviceIdentityMessage,
    trustedDeviceKeys,
    setTrustedDeviceKeys,
    historySearchMessagesByRoom,
    setHistorySearchMessagesByRoom,
    historySearchBusy,
    setHistorySearchBusy,
    terminalLinesByRoom,
    setTerminalLinesByRoom,
    terminalBusyByRoom,
    setTerminalBusyByRoom,
    terminals,
    setTerminals,
    terminalRequestsByRoom,
    setTerminalRequestsByRoom,
    selectedTerminalIdsByRoom,
    setSelectedTerminalIdsByRoom,
    terminalNamesByRoom,
    setTerminalNamesByRoom,
    terminalCommandsByRoom,
    setTerminalCommandsByRoom,
    terminalInputsByRoom,
    setTerminalInputsByRoom,
    terminalErrorsByRoom,
    setTerminalErrorsByRoom,
    terminalAutoOpenedRoomsRef,
    browserRequestsByRoom,
    setBrowserRequestsByRoom,
    browserUrlsByRoom,
    setBrowserUrlsByRoom,
    browserReasonsByRoom,
    setBrowserReasonsByRoom,
    browserMessagesByRoom,
    setBrowserMessagesByRoom,
    browserStatusByRoom,
    setBrowserStatusByRoom,
    activeBrowserUrlsByRoom,
    setActiveBrowserUrlsByRoom,
    gitStatusByRoom,
    setGitStatusByRoom,
    gitWorkflowBusyByRoom,
    setGitWorkflowBusyByRoom,
    gitWorkflowMessagesByRoom,
    setGitWorkflowMessagesByRoom,
    actionsBusyByRoom,
    setActionsBusyByRoom,
    actionsMessagesByRoom,
    setActionsMessagesByRoom,
    actionRunsByRoom,
    setActionRunsByRoom,
    actionsLastCheckedByRoom,
    setActionsLastCheckedByRoom,
    gitWorkflowDraftsByRoom,
    setGitWorkflowDraftsByRoom,
    fileQueriesByRoom,
    setFileQueriesByRoom,
    projectFilesByRoom,
    setProjectFilesByRoom,
    selectedFilesByRoom,
    setSelectedFilesByRoom,
    selectedDiffsByRoom,
    setSelectedDiffsByRoom,
    filePreviewTabsByRoom,
    setFilePreviewTabsByRoom,
    fileBusyByRoom,
    setFileBusyByRoom,
    fileMessagesByRoom,
    setFileMessagesByRoom,
    markdownCopyFallbacksByRoom,
    setMarkdownCopyFallbacksByRoom,
    inviteRequestsByRoom,
    setInviteRequestsByRoom,
    inviteSecretInput,
    setInviteSecretInput,
    inviteLinksByRoom,
    setInviteLinksByRoom,
    inviteApprovalGatesByRoom,
    setInviteApprovalGatesByRoom,
    inviteMessagesByRoom,
    setInviteMessagesByRoom,
    keyRotationBusyByRoom,
    setKeyRotationBusyByRoom,
    inviteAdmissionsByRoom,
    setInviteAdmissionsByRoom,
    sidebarCollapsed,
    inspectorCollapsed,
    shellStyle,
    beginShellResize,
    toggleSidebarCollapsed,
    toggleInspectorCollapsed
  } = useAppStateSlices({
    workspace: {
      initialTeams: seededTeams,
      initialRooms: seededRooms,
      initialTeamMembersByTeam: seededTeamMembers,
      initialProjectPath: defaultProjectPath,
      initialRoomId: "room-desktop",
      initialMessagesByRoom
    },
    historyDefaults: { initialTeamId: seededTeams[0].id },
    terminals: { initialTerminalLinesByRoom }
  });
  const {
    relayRef,
    seenEnvelopeIds,
    historyLoadedRoomIds,
    roomsRef,
    selectedRoomIdRef,
    gitWorkflowDraftsRef,
    hostBusyRef,
    settingsBusyRef,
    keyRotationBusyRef,
    gitWorkflowBusyRef,
    actionsBusyRef,
    terminalBusyRef,
    localPreviewBusyRef,
    fileBusyRef,
    browserRequestsRef
  } = useAppRefs({
    rooms,
    selectedRoomId,
    gitWorkflowDraftsByRoom,
    hostBusyByRoom,
    settingsBusyByRoom,
    keyRotationBusyByRoom,
    gitWorkflowBusyByRoom,
    actionsBusyByRoom,
    localPreviewBusyByRoom,
    fileBusyByRoom,
    terminalBusyByRoom,
    browserRequestsByRoom
  });
  const {
    authConfig,
    currentUser,
    deviceFlow,
    authError,
    authBusy,
    beginGitHubSignIn,
    signOutGitHub
  } = useGitHubAuth(appConfig.relayHttpUrl);
  const { deviceId, localUser } = useLocalIdentity(currentUser);
  const roomSettingsActor = useRoomSettingsActor(localUser);

  const {
    selectedCodexModel,
    hasSelectedRoom,
    selectedRoom,
    inspectorTab,
    secretWarningVisible,
    roomTerminals,
    markdownSelectionMode,
    selectedMessageIds,
    clearSelectedMessages,
    toggleMarkdownSelectionMode,
    toggleMessageSelection,
    selectedTeamName,
    selectedTeamMembersMessage,
    selectedTeamMembersBusy,
    selectedTeamMemberRows,
    customCodexModel,
    projectPathDraft,
    messages,
    draft,
    selectedMessages,
    pendingAttachments,
    pendingAttachmentBytes,
    browserRequests,
    browserUrl,
    browserReason,
    activeBrowserUrl,
    gitStatus,
    gitWorkflowDraft,
    gitWorkflowBusy,
    gitWorkflowMessage,
    actionRuns,
    actionsBusy,
    actionsLastChecked,
    actionsMessage,
    terminalLines,
    terminalBusy,
    selectedTerminalId,
    terminalName,
    terminalCommand,
    terminalInput,
    terminalError,
    fileQuery,
    projectFiles,
    selectedFile,
    selectedDiff,
    filePreviewTab,
    fileBusy,
    fileMessage,
    inviteLink,
    inviteApprovalGate,
    inviteMessage,
    hostMessage,
    chatMessage,
    settingsMessage,
    visibleHistoryMessage,
    markdownCopyFallback
  } = useAppSelectedContext({
    roomContext: {
      rooms,
      selectedRoomId,
      fallbackRoom: emptyRoom,
      inspectorTabsByRoom,
      secretWarningsVisibleByRoom,
      terminals
    },
    markdownSelection: {
      resetKey: selectedRoomId
    },
    teamData: {
      teams,
      selectedTeam,
      teamMembersByTeam,
      teamMembersMessageByTeam,
      teamMembersBusyByTeam,
      currentUser,
      localUserId: localUser.id
    },
    roomValues: {
      selectedRoomId,
      selectedTeam,
      customCodexModelsByRoom,
      projectPathDraftsByRoom,
      messagesByRoom,
      draftsByRoom,
      pendingAttachmentsByRoom,
      browserRequestsByRoom,
      browserUrlsByRoom,
      browserReasonsByRoom,
      activeBrowserUrlsByRoom,
      gitStatusByRoom,
      gitWorkflowDraftsByRoom,
      gitWorkflowBusyByRoom,
      gitWorkflowMessagesByRoom,
      actionRunsByRoom,
      actionsBusyByRoom,
      actionsLastCheckedByRoom,
      actionsMessagesByRoom,
      terminalLinesByRoom,
      terminalBusyByRoom,
      selectedTerminalIdsByRoom,
      terminalNamesByRoom,
      terminalCommandsByRoom,
      terminalInputsByRoom,
      terminalErrorsByRoom,
      fileQueriesByRoom,
      projectFilesByRoom,
      selectedFilesByRoom,
      selectedDiffsByRoom,
      filePreviewTabsByRoom,
      fileBusyByRoom,
      fileMessagesByRoom,
      inviteLinksByRoom,
      inviteApprovalGatesByRoom,
      inviteMessagesByRoom,
      hostMessagesByRoom,
      chatMessagesByRoom,
      settingsMessagesByRoom,
      historyMessagesByRoom,
      teamHistoryMessagesByTeam,
      markdownCopyFallbacksByRoom,
      defaultBrowserUrl,
      defaultBrowserReason
    }
  });
  const {
    setHostMessageForRoom,
    setSelectedHostMessage,
    setChatMessageForRoom,
    setSelectedChatMessage,
    setMarkdownCopyFallbackForRoom,
    setSecretWarningVisibleForRoom,
    setHistoryMessageForRoom,
    setSelectedHistoryMessage,
    setTeamHistoryMessageForTeam,
    setSelectedTeamHistoryMessage,
    setSettingsMessageForRoom,
    setSelectedSettingsMessage,
    setGitWorkflowBusyForRoom,
    setActionsBusyForRoom,
    setLocalPreviewBusyForRoom,
    setHostBusyForRoom,
    setSettingsBusyForRoom,
    setKeyRotationBusyForRoom,
    setFileBusyForRoom,
    setTerminalBusyForRoom,
    setFileQueryForRoom,
    setProjectFilesForRoom,
    setSelectedFileForRoom,
    setSelectedDiffForRoom,
    setFilePreviewTabForRoom,
    setFileMessageForRoom,
    setSelectedFileMessage,
    resetFileContextForRoom,
    setSelectedTerminalIdForRoom,
    setTerminalNameForRoom,
    setTerminalCommandForRoom,
    setTerminalInputForRoom,
    setTerminalErrorForRoom,
    setSelectedTerminalError,
    appendTerminalLinesForRoom,
    setApprovalVisibleForRoom,
    setPendingCodexApprovalForRoom,
    resetCodexApprovalForRoom,
    setCodexRunningForRoom,
    setBrowserUrlForRoom,
    setBrowserReasonForRoom,
    setBrowserMessageForRoom,
    setSelectedBrowserMessage,
    setInviteLinkForRoom,
    setInviteApprovalGateForRoom,
    setInviteMessageForRoom,
    setSelectedInviteMessage,
    setPendingAttachmentsForRoom,
    setDraftForRoom,
    setCustomCodexModelForRoom,
    setProjectPathDraftForRoom,
    setGitWorkflowMessageForRoom,
    setSelectedGitWorkflowMessage,
    setGitStatusForRoom,
    updateSelectedGitWorkflowDraft,
    appendGitWorkflowEvent,
    appendGitHubActionsEvent,
    appendLocalPreviewEvent,
    appendHostHandoff,
    appendInviteRequest,
    appendCodexEvent,
    updateInviteRequestStatus,
    appendTerminalRequest,
    updateTerminalRequestStatus,
    appendBrowserRequest,
    updateBrowserRequestStatus
  } = useRoomScopedSetters({
    messages: {
      selectedRoomId: selectedRoom.id,
      selectedTeamId: selectedTeam,
      setHostMessagesByRoom,
      setChatMessagesByRoom,
      setMarkdownCopyFallbacksByRoom,
      setSecretWarningsVisibleByRoom,
      setHistoryMessagesByRoom,
      setTeamHistoryMessagesByTeam,
      setSettingsMessagesByRoom
    },
    busy: {
      gitWorkflowBusyRef,
      actionsBusyRef,
      localPreviewBusyRef,
      hostBusyRef,
      settingsBusyRef,
      keyRotationBusyRef,
      fileBusyRef,
      terminalBusyRef,
      setGitWorkflowBusyByRoom,
      setActionsBusyByRoom,
      setLocalPreviewBusyByRoom,
      setHostBusyByRoom,
      setSettingsBusyByRoom,
      setKeyRotationBusyByRoom,
      setFileBusyByRoom,
      setTerminalBusyByRoom
    },
    files: {
      selectedRoomId: selectedRoom.id,
      setFileQueriesByRoom,
      setProjectFilesByRoom,
      setSelectedFilesByRoom,
      setSelectedDiffsByRoom,
      setFilePreviewTabsByRoom,
      setFileBusyByRoom,
      setFileMessagesByRoom
    },
    terminals: {
      selectedRoomId: selectedRoom.id,
      maxTerminalActivityLines,
      setSelectedTerminalIdsByRoom,
      setTerminalNamesByRoom,
      setTerminalCommandsByRoom,
      setTerminalInputsByRoom,
      setTerminalErrorsByRoom,
      setTerminalLinesByRoom
    },
    codexApprovals: {
      setApprovalVisibleByRoom,
      setPendingCodexApprovalsByRoom,
      setCodexRunningByRoom
    },
    browser: {
      selectedRoomId: selectedRoom.id,
      defaultBrowserUrl,
      defaultBrowserReason,
      setBrowserUrlsByRoom,
      setBrowserReasonsByRoom,
      setBrowserMessagesByRoom
    },
    invites: {
      selectedRoomId: selectedRoom.id,
      setInviteLinksByRoom,
      setInviteApprovalGatesByRoom,
      setInviteMessagesByRoom
    },
    drafts: {
      setPendingAttachmentsByRoom,
      setDraftsByRoom
    },
    project: {
      roomsRef,
      defaultCodexModel,
      defaultProjectPath,
      setCustomCodexModelsByRoom,
      setProjectPathDraftsByRoom
    },
    git: {
      selectedRoomId: selectedRoom.id,
      hasSelectedRoom,
      setGitWorkflowMessagesByRoom,
      setGitWorkflowDraftsByRoom,
      setGitStatusByRoom
    },
    events: {
      setGitWorkflowEventsByRoom,
      setGitHubActionsEventsByRoom,
      setLocalPreviewsByRoom,
      setHostHandoffsByRoom,
      setInviteRequestsByRoom,
      setCodexEventsByRoom
    },
    requests: {
      setInviteRequestsByRoom,
      setTerminalRequestsByRoom,
      setBrowserRequestsByRoom
    }
  });
  const {
    appendRoomMessage,
    applyMessageReaction
  } = useRoomChatMutations({
    setMessagesByRoom
  });
  const {
    upsertTeam,
    upsertRoom,
    handleRelayError
  } = useWorkspaceRecordActions({
    hasSelectedRoom,
    selectedRoom,
    localUser,
    roomsRef,
    setTeams,
    setTeamMembersByTeam,
    setRooms,
    resetCodexApprovalForRoom,
    setRevokedRoomIds,
    setRevokedTeamIds,
    setForgottenRoomIds,
    setInviteAdmissionsByRoom,
    setPresenceByRoom,
    setInviteLinkForRoom,
    setInviteMessageForRoom,
    setChatMessageForRoom,
    setHostMessageForRoom,
    setWorkspaceError
  });
  const {
    reportRoomHostMutationInFlight,
    reportRoomSettingsMutationInFlight,
    reportRoomKeyRotationInFlight,
    reportRoomFileActionInFlight,
    reportRoomTerminalActionInFlight,
    roomNotices,
    acknowledgeRoomVisibilityWarning,
    isActiveHost,
    isSelectedRoomForgotten,
    isSelectedRoomRevoked,
    isSelectedRoomLocked,
    canReadLocalWorkspace,
    canRequestWorkspace,
    canRequestBrowser,
    canHostBrowser,
    canCopyRoomInvite,
    localWorkspaceMessage,
    roomPosture,
    browserAccessMessage,
    workspaceRequestMessage,
    hostGateMessage,
    roomSettingsGateMessage,
    publishChatMessage,
    toggleMessageReaction,
    actionsSummary,
    githubWorkflowReadiness,
    githubActionsReadiness,
    gitApprovalPreview,
    roomMemberRows
  } = useRoomInteractionContext({
    inFlightReporters: {
      hostBusyRef,
      settingsBusyRef,
      keyRotationBusyRef,
      fileBusyRef,
      terminalBusyRef,
      setHostMessageForRoom,
      setSettingsMessageForRoom,
      setInviteMessageForRoom,
      setFileMessageForRoom,
      setTerminalErrorForRoom
    },
    notices: {
      roomId: selectedRoom.id,
      hostMessage,
      chatMessage,
      setHostMessageForRoom,
      setChatMessageForRoom
    },
    visibilityWarning: {
      hasSelectedRoom,
      selectedRoomId: selectedRoom.id,
      setSecretWarningVisibleForRoom
    },
    access: {
      hasSelectedRoom,
      selectedRoom,
      localUser,
      forgottenRoomIds,
      revokedRoomIds,
      revokedTeamIds,
      historySettings,
      inviteApprovalGate
    },
    chat: {
      hasSelectedRoom,
      selectedRoom,
      forgottenRoomIds,
      revokedRoomIds,
      revokedTeamIds,
      localUser,
      deviceId,
      relayStatus,
      relayRef,
      seenEnvelopeIds,
      appendRoomMessage,
      applyMessageReaction,
      setChatMessageForRoom,
      setSelectedChatMessage
    },
    githubWorkflow: {
      actionRuns,
      authConfig,
      currentUser,
      gitWorkflowDraft,
      projectPath: selectedRoom.projectPath
    },
    memberRows: {
      presenceByRoom,
      selectedRoom,
      selectedRoomId,
      localUser,
      localDeviceId: deviceId,
      localPublicKeyFingerprint: deviceIdentity?.publicKeyFingerprint,
      trustedDeviceKeys
    }
  });
  const {
    activeCodexApproval,
    approvalVisible,
    selectedTerminal,
    selectedTerminalCanRestart,
    hostHandoffs,
    terminalRequests,
    localPreviews,
    localPreviewBusy,
    selectedTerminalCanControl,
    inspectorAttention,
    inviteRequests,
    codexEvents,
    gitWorkflowEvents,
    githubActionsEvents,
    selectedCodexThreadId,
    codexRunning,
    approvalTranscriptMessages,
    codexApprovalSummaryDisplay,
    chatMessageRows,
    pendingAttachmentRows,
    localPreviewCards,
    pendingAttachmentSummary,
    hostBusy,
    settingsBusy,
    keyRotationBusy,
    hostStatusLabel,
    roomCanUseChat
  } = useSelectedRoomRuntime({
    selectedRoom,
    selectedRoomId,
    markdownSelectionMode,
    selectedMessageIds,
    localUser,
    isSelectedRoomLocked,
    messages,
    pendingAttachments,
    pendingAttachmentBytes,
    browserRequests,
    roomTerminals,
    selectedTerminalId,
    pendingCodexApprovalsByRoom,
    approvalVisibleByRoom,
    hostHandoffsByRoom,
    terminalRequestsByRoom,
    localPreviewsByRoom,
    localPreviewBusyByRoom,
    inviteRequestsByRoom,
    codexEventsByRoom,
    gitWorkflowEventsByRoom,
    githubActionsEventsByRoom,
    codexThreadIdsByRoom,
    codexRunningByRoom,
    hostBusyByRoom,
    settingsBusyByRoom,
    keyRotationBusyByRoom
  });
  const {
    setRoomHost,
    acceptHostHandoff,
    publishHostHandoff,
    markHostHandoffAccepted
  } = useHostHandoffActions({
    hasSelectedRoom,
    selectedRoom,
    selectedRoomIdRef,
    isSelectedRoomLocked,
    isSelectedRoomRevoked,
    isActiveHost,
    hostGateMessage,
    hostHandoffs,
    localUser,
    deviceId,
    relayStatus,
    relayRef,
    seenEnvelopeIds,
    messages,
    terminals,
    browserRequestsByRoom,
    gitStatus,
    gitStatusByRoom,
    reportRoomHostMutationInFlight,
    roomSettingsActor,
    setRooms,
    setCodexContinuationByRoom,
    setHostHandoffsByRoom,
    setHostBusyForRoom,
    setHostMessageForRoom,
    setSelectedHostMessage,
    setSettingsMessageForRoom,
    setProjectPathDraftForRoom,
    setCustomCodexModelForRoom,
    resetFileContextForRoom,
    resetCodexApprovalForRoom,
    appendHostHandoff
  });
  const {
    acceptInvite,
    copyInviteLink,
    decryptInviteEnvelope,
    decideInviteJoinRequest,
    handleInviteEnvelopePlaintext,
    joinInviteSecret,
    requestNoSecretInviteAccess,
    rotateSelectedRoomKey
  } = useInviteActions({
    hasSelectedRoom,
    selectedRoom,
    selectedRoomIdRef,
    isSelectedRoomLocked,
    isSelectedRoomRevoked,
    isActiveHost,
    hostGateMessage,
    inviteApprovalGate,
    inviteRequests,
    inviteSecretInput,
    localUser,
    deviceId,
    deviceIdentity,
    relayStatus,
    relayRef,
    seenEnvelopeIds,
    historyLoadedRoomIds,
    reportRoomKeyRotationInFlight,
    upsertTeam,
    upsertRoom,
    appendInviteRequest,
    updateInviteRequestStatus,
    appendRoomMessage,
    setSelectedInviteMessage,
    setInviteMessageForRoom,
    setInviteLinkForRoom,
    setInviteSecretInput,
    setSelectedTeam,
    setSelectedRoomId,
    setForgottenRoomIds,
    setRevokedRoomIds,
    setRevokedTeamIds,
    setInviteAdmissionsByRoom,
    setMessagesByRoom,
    setKeyRotationBusyForRoom
  });

  const {
    selectedAttachmentReview,
    selectedFileRisks,
    selectedFileNeedsAttachmentReview,
    selectedSensitiveFileReviewed,
    terminalRisks,
    terminalCommandRisks,
    terminalOutputLines,
    terminalRequestRows,
    codexEventRows,
    searchActive,
    sidebarTeamRows,
    sidebarRoomRows,
    sidebarMessageHitRows,
    refreshTeamMembers
  } = useRoomDisplayContext({
    fileTerminal: {
      selectedFile,
      selectedRoomId: selectedRoom.id,
      selectedRoomProjectPath: selectedRoom.projectPath,
      sensitiveAttachmentReviewKey,
      selectedTerminal,
      terminalLines,
      terminalCommand,
      terminalRequests,
      codexEvents
    },
    sidebar: {
      sidebarQuery,
      rooms,
      teams,
      selectedTeam,
      selectedRoomId,
      messagesByRoom,
      historySearchMessagesByRoom,
      approvalVisibleByRoom,
      terminalRequestsByRoom,
      browserRequestsByRoom,
      approvalPolicyLabels
    },
    teamMembers: {
      selectedTeam,
      relayHttpUrl: appConfig.relayHttpUrl,
      setTeamMembersByTeam,
      setTeamMembersMessageByTeam
    }
  });
  const workspaceFlow = useWorkspaceFlowContext({
    bootstrap: {
      workspace: {
        relayHttpUrl: appConfig.relayHttpUrl,
        setTeams,
        setRooms,
        setSelectedTeam,
        setSelectedRoomId,
        setWorkspaceError
      },
      selectedRoomReadReceipt: {
        selectedRoomId,
        setRooms
      },
      deviceIdentity: {
        relayHttpUrl: appConfig.relayHttpUrl,
        deviceId,
        userId: localUser.id,
        displayName: localUser.name,
        deviceIdentity,
        setDeviceIdentity,
        setDeviceIdentityMessage
      },
      selectedTeamDefaults: {
        selectedTeam,
        setTeamHistorySettings,
        setTeamDefaultApprovalPolicy,
        setTeamDefaultCodexModel,
        setTeamDefaultBrowserProfilePersistent,
        setTeamDefaultInviteApprovalGate
      },
      inviteUrl: {
        requestNoSecretInviteAccess,
        acceptInvite,
        setSelectedInviteMessage
      }
    },
    markdownCopy: {
      hasSelectedRoom,
      canReadLocalWorkspace,
      localWorkspaceMessage,
      selectedRoom,
      teams,
      messages,
      selectedMessages,
      gitStatus,
      selectedFile,
      selectedDiff,
      selectedFileRisks,
      selectedTerminal,
      terminalLines,
      terminalRisks,
      setMarkdownCopyFallbackForRoom,
      setSelectedChatMessage,
      setChatMessageForRoom,
      setSelectedFileMessage,
      setFileMessageForRoom,
      setSelectedTerminalError,
      setTerminalErrorForRoom,
      setSelectedGitWorkflowMessage,
      setGitWorkflowMessageForRoom
    },
    workspaceRoomActions: {
      members: {
        selectedTeam,
        selectedTeamName,
        selectedTeamMembersBusy,
        selectedRoom,
        localUser,
        currentUser,
        setDeviceIdentityMessage,
        setTrustedDeviceKeys,
        setTeamMembersBusyByTeam,
        setTeamMembersMessageByTeam,
        setTeamMembersByTeam,
        setTeams
      },
      workspaceCreation: {
        selectedTeam,
        newTeamName,
        newRoomName,
        newRoomProjectPath,
        setWorkspaceError,
        setSelectedTeam,
        setSelectedRoomId,
        setNewTeamName,
        setNewRoomName,
        setNewRoomProjectPath,
        setRevokedRoomIds,
        setRevokedTeamIds,
        setForgottenRoomIds,
        setMessagesByRoom,
        setInviteApprovalGateForRoom,
        upsertTeam,
        upsertRoom
      },
      teamDefaults: {
        selectedTeam,
        approvalPolicyLabels,
        setSelectedTeamHistoryMessage,
        setTeamHistoryMessageForTeam,
        setTeamHistorySettings,
        setTeamDefaultApprovalPolicy,
        setTeamDefaultCodexModel,
        setTeamDefaultBrowserProfilePersistent,
        setTeamDefaultInviteApprovalGate
      },
      localHistory: {
        hasSelectedRoom,
        selectedRoom,
        selectedRoomIdRef,
        isSelectedRoomLocked,
        isSelectedRoomRevoked,
        isActiveHost,
        messages,
        terminalRequests,
        browserRequests,
        inviteRequests,
        codexEvents,
        gitWorkflowEvents,
        githubActionsEvents,
        localPreviews,
        terminals,
        hostHandoffs,
        selectedCodexThreadId,
        reportRoomSettingsMutationInFlight,
        roomSettingsActor,
        setSelectedHistoryMessage,
        setHistoryMessageForRoom,
        setInviteApprovalGateForRoom,
        setSettingsBusyForRoom,
        setSecretWarningVisibleForRoom,
        setHistorySettings,
        setMessagesByRoom,
        setTerminalRequestsByRoom,
        setBrowserRequestsByRoom,
        setInviteRequestsByRoom,
        setCodexEventsByRoom,
        setGitWorkflowEventsByRoom,
        setGitHubActionsEventsByRoom,
        setLocalPreviewsByRoom,
        setTerminals,
        setHostHandoffsByRoom,
        setRooms,
        setBrowserStatusByRoom,
        setActiveBrowserUrlsByRoom,
        setCodexThreadIdsByRoom,
        setActionRunsByRoom,
        setActionsLastCheckedByRoom,
        setActionsMessagesByRoom,
        setActionsBusyByRoom,
        setGitWorkflowBusyByRoom,
        setHostBusyByRoom,
        setHostMessagesByRoom,
        setChatMessagesByRoom,
        setMarkdownCopyFallbacksByRoom,
        setSecretWarningsVisibleByRoom,
        setHistoryMessagesByRoom,
        setSettingsBusyByRoom,
        setSettingsMessagesByRoom,
        setCustomCodexModelsByRoom,
        setProjectPathDraftsByRoom,
        setKeyRotationBusyByRoom,
        setApprovalVisibleByRoom,
        setPendingCodexApprovalsByRoom,
        setCodexRunningByRoom,
        setGitStatusByRoom,
        setFileQueriesByRoom,
        setProjectFilesByRoom,
        setSelectedFilesByRoom,
        setSelectedDiffsByRoom,
        setFileBusyByRoom,
        setFileMessagesByRoom,
        setPendingAttachmentsByRoom,
        setTerminalLinesByRoom,
        setTerminalBusyByRoom,
        setSelectedTerminalIdsByRoom,
        setTerminalNamesByRoom,
        setTerminalCommandsByRoom,
        setTerminalInputsByRoom,
        setTerminalErrorsByRoom,
        setBrowserUrlsByRoom,
        setBrowserReasonsByRoom,
        setBrowserMessagesByRoom,
        setInviteLinksByRoom,
        setInviteApprovalGatesByRoom,
        setInviteMessagesByRoom,
        setDraftsByRoom,
        setForgottenRoomIds,
        historyLoadedRoomIds
      },
      files: {
        hasSelectedRoom,
        canReadLocalWorkspace,
        localWorkspaceMessage,
        selectedRoom,
        selectedRoomIdRef,
        isSelectedRoomLocked,
        isSelectedRoomRevoked,
        selectedFile,
        pendingAttachmentsByRoom,
        sensitiveAttachmentReviewKey,
        setSensitiveAttachmentReviewKey,
        reportRoomFileActionInFlight,
        setFileBusyForRoom,
        setSelectedFileForRoom,
        setSelectedDiffForRoom,
        setFilePreviewTabForRoom,
        setSelectedFileMessage,
        setFileMessageForRoom,
        setPendingAttachmentsForRoom,
        setInspectorTabsByRoom
      }
    },
    historyEffects: {
    hydration: {
      hasSelectedRoom,
      selectedRoomId,
      selectedRoomTeamId: selectedRoom.teamId,
      forgottenRoomIds,
      historyLoadedRoomIds,
      setHistorySettings,
      setMessagesByRoom,
      setTerminalRequestsByRoom,
      setBrowserRequestsByRoom,
      setInviteRequestsByRoom,
      setCodexEventsByRoom,
      setGitWorkflowEventsByRoom,
      setGitHubActionsEventsByRoom,
      setLocalPreviewsByRoom,
      setGitWorkflowMessageForRoom,
      setActionRunsByRoom,
      setActionsLastCheckedByRoom,
      setActionsMessagesByRoom,
      setTerminals,
      setSelectedTerminalIdsByRoom,
      setHostHandoffsByRoom,
      setCodexThreadIdsByRoom
    },
    search: {
      searchActive,
      rooms,
      forgottenRoomIds,
      revokedRoomIds,
      revokedTeamIds,
      setHistorySearchMessagesByRoom,
      setHistorySearchBusy
    }
    }
  });

  const {
    handleCodexBrowserOpenCommand,
    publishRequestStatus,
    publishLocalPreviewEvent,
    publishTerminalResult,
    publishGitWorkflowEvent,
    publishCodexEvent,
    publishRoomSettingsEvent,
    publishGitHubActionsEvent
  } = useRelaySyncContext({
    browserOpenCommand: {
      localUser,
      selectedRoomIdRef,
      forgottenRoomIds,
      revokedRoomIds,
      revokedTeamIds,
      appendBrowserRequest,
      setBrowserMessageForRoom,
      setBrowserUrlForRoom,
      setActiveBrowserUrlsByRoom,
      setBrowserStatusByRoom,
      setInspectorTabsByRoom
    },
    relayRoomSync: {
      subscription: {
        relayWsUrl: appConfig.relayWsUrl,
        deviceId,
        localUser,
        devicePublicKeyFingerprint: deviceIdentity?.publicKeyFingerprint,
        selectedTeam,
        selectedRoom,
        hasSelectedRoom,
        isActiveHost,
        inviteAdmissionsByRoom,
        revokedRoomIds,
        revokedTeamIds,
        approvalPolicyLabels,
        roomModeLabels,
        relayRef,
        seenEnvelopeIds,
        roomsRef,
        selectedRoomIdRef,
        historyLoadedRoomIds,
        setRelayStatus,
        setPresenceByRoom,
        setRooms,
        setMessagesByRoom,
        setTerminalRequestsByRoom,
        setBrowserRequestsByRoom,
        setActionRunsByRoom,
        setActionsLastCheckedByRoom,
        setActionsMessagesByRoom,
        setForgottenRoomIds,
        handleRelayError,
        upsertRoom,
        upsertTeam,
        refreshTeamMembers,
        decryptInviteEnvelope,
        handleInviteEnvelopePlaintext,
        applyMessageReaction,
        updateTerminalRequestStatus,
        appendTerminalLinesForRoom,
        appendGitWorkflowEvent,
        setGitWorkflowMessageForRoom,
        appendGitHubActionsEvent,
        appendCodexEvent,
        updateBrowserRequestStatus,
        appendLocalPreviewEvent,
        setChatMessageForRoom,
        markHostHandoffAccepted,
        setHostMessageForRoom,
        appendHostHandoff,
        appendRoomMessage,
        setInviteMessageForRoom
      },
      publishers: {
        relayRef,
        seenEnvelopeIds,
        relayStatus,
        selectedRoom,
        deviceId,
        localUser,
        approvalPolicyLabels,
        roomModeLabels,
        appendLocalPreviewEvent,
        appendGitWorkflowEvent,
        appendCodexEvent,
        appendTerminalLinesForRoom,
        appendRoomMessage,
        appendGitHubActionsEvent
      }
    }
  });
  const roomRuntime = useRoomRuntimeContext({
    codexActions: {
      turn: {
      selectedRoom,
      activeCodexApproval,
      roomsRef,
      selectedRoomIdRef,
      forgottenRoomIds,
      revokedRoomIds,
      revokedTeamIds,
      localUser,
      messagesByRoom,
      terminals,
      browserRequestsByRoom,
      gitStatusByRoom,
      codexContinuationByRoom,
      codexThreadIdsByRoom,
      setHostMessageForRoom,
      setPendingCodexApprovalForRoom,
      setApprovalVisibleForRoom,
      setCodexRunningForRoom,
      appendTerminalLinesForRoom,
      setCodexThreadIdsByRoom,
      setCodexContinuationByRoom,
      setRooms,
      publishCodexEvent,
      publishChatMessage,
      publishHostHandoff
    },
      invoke: {
      hasSelectedRoom,
      selectedRoom,
      selectedRoomIdRef,
      isSelectedRoomLocked,
      isSelectedRoomRevoked,
      isActiveHost,
      canReadLocalWorkspace,
      hostGateMessage,
      localUser,
      draft,
      pendingAttachments,
      messages,
      roomTerminals,
      browserRequests,
      gitStatus,
      publishChatMessage,
      handleCodexBrowserOpenCommand,
      setSelectedChatMessage,
      setChatMessageForRoom,
      setSelectedHostMessage,
      setHostMessageForRoom,
      setPendingCodexApprovalForRoom,
      setApprovalVisibleForRoom,
      setDraftForRoom,
      setPendingAttachmentsForRoom
      }
    },
    toolActions: {
      settings: {
      hasSelectedRoom,
      isSelectedRoomLocked,
      isSelectedRoomRevoked,
      isActiveHost,
      selectedRoom,
      selectedRoomIdRef,
      selectedCodexModel,
      projectPathDraft,
      approvalPolicyLabels,
      roomModeLabels,
      roomSettingsGateMessage,
      roomSettingsActor,
      reportRoomSettingsMutationInFlight,
      setSettingsBusyForRoom,
      setSelectedSettingsMessage,
      setSettingsMessageForRoom,
      setSelectedBrowserMessage,
      setBrowserMessageForRoom,
      setRooms,
      setBrowserStatusByRoom,
      setProjectPathDraftForRoom,
      resetCodexApprovalForRoom,
      resetFileContextForRoom,
      publishRoomSettingsEvent
    },
    terminal: {
      hasSelectedRoom,
      isActiveHost,
      canReadLocalWorkspace,
      canRequestWorkspace,
      hostGateMessage,
      localWorkspaceMessage,
      workspaceRequestMessage,
      selectedRoom,
      selectedRoomIdRef,
      isSelectedRoomLocked,
      localUser,
      deviceId,
      relayStatus,
      relayRef,
      seenEnvelopeIds,
      roomTerminals,
      selectedTerminal,
      terminalName,
      terminalCommand,
      terminalInput,
      terminalRequests,
      reportRoomTerminalActionInFlight,
      setTerminalBusyForRoom,
      setSelectedTerminalError,
      setTerminalErrorForRoom,
      appendTerminalLinesForRoom,
      setGitStatusForRoom,
      setTerminals,
      setSelectedTerminalIdForRoom,
      setTerminalNameForRoom,
      setTerminalCommandForRoom,
      setTerminalInputForRoom,
      appendTerminalRequest,
      updateTerminalRequestStatus,
      publishRequestStatus,
      publishTerminalResult
    },
    localPreview: {
      hasSelectedRoom,
      isSelectedRoomLocked,
      isSelectedRoomRevoked,
      selectedRoom,
      rooms,
      localUser,
      localPreviewDialog,
      localPreviewsByRoom,
      setLocalPreviewDialog,
      setLocalPreviewBusyForRoom,
      setSelectedChatMessage,
      setChatMessageForRoom,
      publishLocalPreviewEvent
    },
    account: {
      selectedRoomId: selectedRoom.id,
      deviceId,
      signOutGitHub,
      setDeviceIdentity,
      setDeviceIdentityMessage,
      setTrustedDeviceKeys
    },
    githubActions: {
      hasSelectedRoom,
      selectedRoom,
      roomsRef,
      actionsBusyRef,
      gitWorkflowDraftsRef,
      forgottenRoomIds,
      revokedRoomIds,
      revokedTeamIds,
      localUser,
      authConfig,
      currentUser,
      setActionsBusyForRoom,
      setActionsMessagesByRoom,
      setActionRunsByRoom,
      setActionsLastCheckedByRoom,
      publishGitHubActionsEvent
    },
    gitWorkflow: {
      hasSelectedRoom,
      isActiveHost,
      canReadLocalWorkspace,
      hostGateMessage,
      localWorkspaceMessage,
      selectedRoom,
      gitWorkflowBusyRef,
      gitWorkflowDraft,
      gitApprovalPreview,
      githubWorkflowReadiness,
      messages,
      gitStatus,
      setSelectedGitWorkflowMessage,
      setGitWorkflowMessageForRoom,
      setGitWorkflowBusyForRoom,
      appendTerminalLinesForRoom,
      setGitStatusForRoom,
      publishGitWorkflowEvent
    },
    browser: {
      hasSelectedRoom,
      isActiveHost,
      canRequestBrowser,
      canHostBrowser,
      browserAccessMessage,
      hostGateMessage,
      selectedRoom,
      selectedRoomIdRef,
      browserUrl,
      browserReason,
      browserRequests,
      localUser,
      deviceId,
      relayStatus,
      relayRef,
      seenEnvelopeIds,
      defaultBrowserStatus,
      setSelectedBrowserMessage,
      setBrowserMessageForRoom,
      setBrowserUrlForRoom,
      appendBrowserRequest,
      updateBrowserRequestStatus,
      publishRequestStatus,
      setActiveBrowserUrlsByRoom,
      setBrowserStatusByRoom,
      setInspectorTabsByRoom
      }
    },
    backgroundEffects: {
      localHistoryPersistence: {
      hasSelectedRoom,
      selectedRoomId,
      selectedRoomTeamId: selectedRoom.teamId,
      forgottenRoomIds,
      revokedRoomIds,
      revokedTeamIds,
      historyLoadedRoomIds,
      historySettings,
      messages,
      terminalRequests,
      browserRequests,
      inviteRequests,
      codexEvents,
      gitWorkflowEvents,
      githubActionsEvents,
      localPreviews,
      terminals,
      hostHandoffs,
      selectedCodexThreadId
    },
    localPreviewPolling: {
      localPreviewsByRoom,
      localUserId: localUser.id,
      roomsRef,
      publishLocalPreviewEvent
    },
    roomGitStatusRefresh: {
      hasSelectedRoom,
      canReadLocalWorkspace,
      selectedRoomId: selectedRoom.id,
      selectedRoomProjectPath: selectedRoom.projectPath,
      setGitStatusForRoom
    },
    gitHubRemoteInference: {
      hasSelectedRoom,
      canReadLocalWorkspace,
      selectedRoomId: selectedRoom.id,
      selectedRoomProjectPath: selectedRoom.projectPath,
      selectedRoomIdRef,
      gitWorkflowDraftsRef,
      setGitWorkflowDraftsByRoom,
      setGitWorkflowMessageForRoom
    },
    gitHubActionsDraftReset: {
      hasSelectedRoom,
      selectedRoomId: selectedRoom.id,
      gitWorkflowDraft,
      setActionRunsByRoom,
      setActionsLastCheckedByRoom,
      setActionsMessagesByRoom,
      setActionsBusyByRoom
    },
    projectFilesSearch: {
      hasSelectedRoom,
      canReadLocalWorkspace,
      selectedRoomId: selectedRoom.id,
      selectedRoomProjectPath: selectedRoom.projectPath,
      fileQueriesByRoom,
      localWorkspaceMessage,
      setProjectFilesForRoom,
      setSelectedFileForRoom,
      setSelectedDiffForRoom,
      setFileBusyForRoom,
      setFileMessageForRoom
    },
    terminalLifecycle: {
      hasSelectedRoom,
      canReadLocalWorkspace,
      selectedRoomId: selectedRoom.id,
      selectedTerminalId,
      selectedTerminalRunning: selectedTerminal?.running,
      setTerminals,
      setSelectedTerminalIdsByRoom,
      setSelectedTerminalIdForRoom,
      setTerminalErrorForRoom
    },
    terminalAutoOpen: {
      inspectorTab,
      hasSelectedRoom,
      isActiveHost,
      canReadLocalWorkspace,
      isSelectedRoomLocked,
      terminalBusy,
      roomTerminalCount: roomTerminals.length,
      selectedRoomId: selectedRoom.id,
      terminalAutoOpenedRoomsRef
    },
    codexProbe: { setCodexProbe },
    roomDraftCleanup: {
      hasSelectedRoom,
      selectedRoomId: selectedRoom.id,
      selectedRoomProjectPath: selectedRoom.projectPath,
      selectedCodexModel,
      setCustomCodexModelsByRoom,
      setProjectPathDraftsByRoom
      }
    }
  });

  const {
    roomChatPanelActions,
    roomHeaderActions,
    terminalPanelActions,
    workspaceFilesPanelActions
  } = useRoomPanelActions({
    chat: {
      selectedRoomId: selectedRoom.id,
      messages,
      localPreviews,
      copyMessageMarkdown: workspaceFlow.copyMessageMarkdown,
      copyCodexOutputMarkdown: workspaceFlow.copyCodexOutputMarkdown,
      openEncryptedAttachmentBlob: workspaceFlow.openEncryptedAttachmentBlob,
      toggleMessageReaction,
      setPendingCodexApprovalForRoom,
      setApprovalVisibleForRoom,
      approveCodexTurn: roomRuntime.approveCodexTurn,
      handleCodexInvoke: roomRuntime.handleCodexInvoke,
      copyMarkdownWithFallback: workspaceFlow.copyMarkdownWithFallback,
      setChatMessageForRoom,
      stopLocalPreview: roomRuntime.stopLocalPreview,
      setDraftForRoom
    },
    header: {
      rooms,
      selectedRoomId,
      selectedRoomIdForTabs: selectedRoom.id,
      activeBrowserUrl,
      setSelectedTeam,
      setSelectedRoomId,
      setInspectorTabsByRoom,
      openRoomBrowserNow: roomRuntime.openRoomBrowserNow
    },
    terminal: {
      selectedRoomId: selectedRoom.id,
      terminalRequests,
      copyTerminalMarkdown: workspaceFlow.copyTerminalMarkdown,
      runApprovedTerminalCheck: roomRuntime.runApprovedTerminalCheck,
      openInteractiveTerminal: roomRuntime.openInteractiveTerminal,
      setTerminalNameForRoom,
      setTerminalCommandForRoom,
      startNamedTerminal: roomRuntime.startNamedTerminal,
      requestTerminalCommand: roomRuntime.requestTerminalCommand,
      approveTerminalRequest: roomRuntime.approveTerminalRequest,
      denyTerminalRequest: roomRuntime.denyTerminalRequest,
      setSelectedTerminalIdForRoom,
      setTerminalInputForRoom,
      sendTerminalInput: roomRuntime.sendTerminalInput,
      restartSelectedTerminal: roomRuntime.restartSelectedTerminal,
      stopSelectedTerminal: roomRuntime.stopSelectedTerminal
    },
    workspaceFiles: {
      selectedRoomId: selectedRoom.id,
      copyProjectMarkdown: workspaceFlow.copyProjectMarkdown,
      setFileQueryForRoom,
      openProjectFile: workspaceFlow.openProjectFile,
      copyDiffSummaryMarkdown: workspaceFlow.copyDiffSummaryMarkdown,
      attachSelectedFileToMessage: workspaceFlow.attachSelectedFileToMessage,
      setFilePreviewTabForRoom,
      setSelectedFileForRoom,
      setSelectedDiffForRoom,
      setSensitiveAttachmentReviewKey
    }
  });
  const { appShellViewProps } = useAppViewProps({
    shell: {
      sidebarCollapsed,
      inspectorCollapsed,
      shellStyle,
      onBeginSidebarResize: (event) => beginShellResize("sidebar", event),
      onBeginInspectorResize: (event) => beginShellResize("inspector", event),
      onToggleSidebarCollapsed: toggleSidebarCollapsed,
      onToggleInspectorCollapsed: toggleInspectorCollapsed
    },
    roomMainColumn: {
    teamRecords: teams,
    selectedTeam,
    selectedRoom,
    localUser,
    hostBusy,
    isActiveHost,
    isSelectedRoomLocked,
    isSelectedRoomRevoked,
    hasSelectedRoom,
    selectedCodexModel,
    modelOptions: codexModelOptions,
    settingsBusy,
    selectedMessages,
    markdownSelectionMode,
    inspectorTab,
    roomHeaderActions,
    onSetHost: setRoomHost,
    onRenameRoom: roomRuntime.renameRoom,
    onSelectModel: roomRuntime.setCodexModel,
    onCopyRoomMarkdown: workspaceFlow.copyRoomMarkdown,
    onCopySelectedMarkdown: workspaceFlow.copySelectedMessagesMarkdown,
    onToggleMarkdownSelection: toggleMarkdownSelectionMode,
    onClearSelectedMessages: clearSelectedMessages,
    onShareLocalPreview: roomRuntime.openLocalPreviewDialog,
    notices: roomNotices,
    secretWarningVisible,
    onAcknowledgeSecretWarning: acknowledgeRoomVisibilityWarning,
    markdownCopyFallback,
    copyMarkdownWithFallback: workspaceFlow.copyMarkdownWithFallback,
    setChatMessageForRoom,
    setMarkdownCopyFallbackForRoom,
    messages: chatMessageRows,
    approvalVisible,
    approvalSummary: codexApprovalSummaryDisplay,
    codexRunning,
    roomCanUseChat,
    draft,
    pendingAttachmentsForCount: pendingAttachments,
    pendingAttachments: pendingAttachmentRows,
    localPreviewCards,
    pendingAttachmentSummary,
    onToggleMessageSelection: toggleMessageSelection,
    onRemovePendingAttachment: workspaceFlow.removePendingAttachment,
    onSendMessage: roomRuntime.sendMessage,
    roomChatPanelActions
    },
    roomInspectorPanel: {
    activeTab: inspectorTab,
    activeBrowserUrl,
    browserUrl,
    canHostBrowser,
    onBrowserUrlChange: (url) => setBrowserUrlForRoom(selectedRoom.id, url),
    onOpenBrowserNow: roomRuntime.openRoomBrowserNow,
    selectedRoom,
    projectPathDraft,
    gitStatus,
    hasSelectedRoom,
    isSelectedRoomLocked,
    settingsBusy,
    isActiveHost,
    defaultProjectPath,
    onProjectPathDraftChange: (path) => setProjectPathDraftForRoom(selectedRoom.id, path),
    onChooseProjectPath: roomRuntime.chooseProjectPath,
    onUpdateProjectPath: roomRuntime.updateProjectPath,
    teamRoster: {
      members: selectedTeamMemberRows,
      hasSelectedTeam: Boolean(selectedTeam),
      busy: selectedTeamMembersBusy,
      message: selectedTeamMembersMessage,
      onPromote: (member) => workspaceFlow.changeTeamMemberRole(member, "admin"),
      onDemote: (member) => workspaceFlow.changeTeamMemberRole(member, "member"),
      onTransferOwnership: workspaceFlow.transferOwnershipToTeamMember,
      onRemove: workspaceFlow.removeMemberFromTeam
    },
    roomMembers: {
      members: roomMemberRows,
      localDeviceId: deviceId,
      message: deviceIdentityMessage,
      onCopyFingerprint: (member) => workspaceFlow.copyRoomMemberDeviceFingerprint(member, member.trusted),
      onTrust: workspaceFlow.trustRoomMemberDevice,
      onUntrust: workspaceFlow.untrustRoomMemberDevice
    },
    hostHandoffs,
    hostBusy,
    onAcceptHandoff: acceptHostHandoff,
    encryptedInvite: {
      inviteApprovalGate,
      copyDisabled: !canCopyRoomInvite,
      inviteSecretInput,
      inviteRequests,
      localDeviceId: deviceId,
      gateDisabled: !hasSelectedRoom || isSelectedRoomLocked,
      importDisabled: !inviteSecretInput.trim(),
      rotateDisabled: !hasSelectedRoom || isSelectedRoomLocked || !isActiveHost || keyRotationBusy,
      approvalDisabled: !hasSelectedRoom || isSelectedRoomLocked || !isActiveHost,
      keyRotationBusy,
      inviteLink,
      inviteMessage,
      onCopyInvite: copyInviteLink,
      onInviteApprovalGateChange: (enabled) => setInviteApprovalGateForRoom(selectedRoom.id, enabled),
      onInviteSecretInputChange: setInviteSecretInput,
      onImportInvite: joinInviteSecret,
      onRotateRoomKey: rotateSelectedRoomKey,
      onDecideInviteRequest: decideInviteJoinRequest
    },
    approvalPolicy: {
      labels: approvalPolicyLabels,
      message: settingsMessage,
      onSelectPolicy: roomRuntime.setApprovalPolicy
    },
    roomMode: {
      labels: roomModeLabels,
      onToggleMode: roomRuntime.toggleRoomMode
    },
    selectedCodexModel,
    customCodexModel,
    model: {
      customModel: customCodexModel,
      modelOptions: codexModelOptions,
      onSelectModel: roomRuntime.setCodexModel,
      onCustomModelChange: (model) => setCustomCodexModelForRoom(selectedRoom.id, model),
      onApplyCustomModel: () => roomRuntime.setCodexModel(customCodexModel)
    },
    localHistory: {
      historySettings,
      teamHistorySettings,
      selectedTeam: Boolean(selectedTeam),
      hasSelectedRoom,
      settingsBusy,
      teamDefaultApprovalPolicy,
      approvalPolicyLabels,
      teamDefaultCodexModel,
      defaultCodexModel,
      codexModelOptions,
      teamDefaultBrowserProfilePersistent,
      teamDefaultInviteApprovalGate,
      message: visibleHistoryMessage,
      onHistoryEnabledChange: (enabled) =>
        workspaceFlow.updateLocalHistorySettings({
          ...historySettings,
          enabled
        }),
      onHistoryRetentionDaysChange: (retentionDays) =>
        workspaceFlow.updateLocalHistorySettings({
          ...historySettings,
          retentionDays
        }),
      onClearRoomHistory: workspaceFlow.clearRoomHistory,
      onForgetRoomLocalData: workspaceFlow.forgetSelectedRoomLocalData,
      onApplyTeamDefaultsToRoom: workspaceFlow.applyTeamDefaultsToRoom,
      onTeamHistoryEnabledChange: (enabled) =>
        workspaceFlow.updateTeamHistoryDefaults({
          ...teamHistorySettings,
          enabled
        }),
      onTeamHistoryRetentionDaysChange: (retentionDays) =>
        workspaceFlow.updateTeamHistoryDefaults({
          ...teamHistorySettings,
          retentionDays
        }),
      onTeamDefaultApprovalPolicyChange: workspaceFlow.updateTeamDefaultApprovalPolicy,
      onTeamDefaultCodexModelChange: workspaceFlow.updateTeamDefaultCodexModel,
      onTeamDefaultBrowserProfilePersistentChange: setTeamDefaultBrowserProfilePersistent,
      onTeamDefaultInviteApprovalGateChange: workspaceFlow.updateTeamDefaultInviteApprovalGate
    },
    workspaceFiles: {
      fileQuery,
      projectFiles,
      selectedFile,
      selectedDiff,
      fileBusy,
      fileMessage,
      canReadLocalWorkspace,
      selectedFileRisks,
      selectedFileNeedsAttachmentReview,
      selectedSensitiveFileReviewed,
      selectedAttachmentActionLabel: selectedAttachmentReview?.actionLabel ?? "Attach",
      selectedAttachmentWarningDetail: selectedAttachmentReview?.warningDetail ?? undefined,
      filePreviewTab,
      ...workspaceFilesPanelActions
    },
    gitHandoff: {
      draft: gitWorkflowDraft,
      preview: gitApprovalPreview,
      readiness: githubWorkflowReadiness,
      canReadLocalWorkspace,
      gitWorkflowBusy,
      isActiveHost,
      message: gitWorkflowMessage,
      onDraftChange: updateSelectedGitWorkflowDraft,
      onCopyPullRequestDraftMarkdown: workspaceFlow.copyPullRequestDraftMarkdown,
      onApproveGitWorkflow: roomRuntime.approveGitWorkflow
    },
    githubActions: {
      summary: actionsSummary,
      readiness: githubActionsReadiness,
      runs: actionRuns,
      owner: gitWorkflowDraft.prOwner,
      repo: gitWorkflowDraft.prRepo,
      branch: gitWorkflowDraft.branchName,
      lastChecked: actionsLastChecked,
      busy: actionsBusy,
      refreshDisabled: !canReadLocalWorkspace || actionsBusy || !isActiveHost || !githubActionsReadiness.ready,
      currentUserSignedIn: Boolean(currentUser),
      message: actionsMessage,
      onRefresh: () => roomRuntime.refreshGitHubActions()
    },
    terminal: {
      terminalName,
      terminalCommand,
      terminalInput,
      terminalBusy,
      terminalError,
      terminalCommandRisks,
      terminalRisks,
      codexEvents: codexEventRows,
      commandRequests: terminalRequestRows,
      roomTerminals,
      selectedTerminal,
      selectedTerminalId,
      selectedTerminalCanControl,
      selectedTerminalCanRestart,
      terminalOutputLines,
      codexRunning,
      canReadLocalWorkspace,
      canRequestWorkspace,
      ...terminalPanelActions
    }
    },
    appSidebar: {
    currentUser,
    authBusy,
    authConfig,
    authError,
    deviceFlow,
    sidebarQuery,
    searchActive,
    workspaceError,
    newTeamName,
    newRoomName,
    newRoomProjectPath,
    selectedTeamId: selectedTeam,
    teams: sidebarTeamRows,
    rooms: sidebarRoomRows,
    messageHits: sidebarMessageHitRows,
    historySearchBusy,
    activeSidebarPanel,
    themeMode,
    localUserName: localUser.name,
    selectedRoomName: selectedRoom.name,
    deviceId,
    deviceIdentity,
    deviceIdentityMessage,
    relayStatus,
    relayWsUrl: appConfig.relayWsUrl,
    relayHttpUrl: appConfig.relayHttpUrl,
    codexProbe,
    projectPath: selectedRoom.projectPath,
    selectedCodexModel,
    selectedRoomApprovalPolicy: selectedRoom.approvalPolicy,
    roomPosture,
    hasSelectedRoom,
    isSelectedRoomLocked,
    settingsBusy,
    isActiveHost,
    relayHttpDraft,
    relayWsDraft,
    selectedRoomMode: selectedRoom.mode,
    roomSettingsGateMessage,
    historySettings,
    teamHistorySettings,
    teamDefaultApprovalPolicy,
    teamDefaultCodexModel,
    teamDefaultBrowserProfilePersistent,
    teamDefaultInviteApprovalGate,
    appConfigMessage,
    roomSettingsMessage: settingsMessage,
    historyMessage: visibleHistoryMessage,
    onSignIn: beginGitHubSignIn,
    onSignOut: roomRuntime.signOut,
    onSidebarQueryChange: setSidebarQuery,
    onNewTeamNameChange: setNewTeamName,
    onCreateTeam: workspaceFlow.addTeam,
    onSelectTeam: setSelectedTeam,
    onNewRoomNameChange: setNewRoomName,
    onNewRoomProjectPathChange: setNewRoomProjectPath,
    onChooseNewRoomProjectPath: workspaceFlow.chooseNewRoomProjectPath,
    onCreateRoom: workspaceFlow.addRoom,
    onSelectRoom: setSelectedRoomId,
    onSelectSidebarPanel: setActiveSidebarPanel,
    onToggleTheme: toggleThemeMode,
    onRotateDeviceIdentity: roomRuntime.rotateDeviceIdentity,
    onChooseProject: roomRuntime.chooseProjectPath,
    onRelayHttpDraftChange: setRelayHttpDraft,
    onRelayWsDraftChange: setRelayWsDraft,
    onResetRelay: resetRelayConfiguration,
    onSaveRelay: saveRelayConfiguration,
    onToggleRoomMode: roomRuntime.toggleRoomMode,
    onHistorySettingsChange: workspaceFlow.updateLocalHistorySettings,
    onClearRoomHistory: workspaceFlow.clearRoomHistory,
    onForgetRoomLocalData: workspaceFlow.forgetSelectedRoomLocalData,
    onTeamHistoryDefaultsChange: workspaceFlow.updateTeamHistoryDefaults,
    onTeamDefaultApprovalPolicyChange: workspaceFlow.updateTeamDefaultApprovalPolicy,
    onTeamDefaultCodexModelChange: workspaceFlow.updateTeamDefaultCodexModel,
    onTeamDefaultBrowserProfilePersistentChange: setTeamDefaultBrowserProfilePersistent,
    onTeamDefaultInviteApprovalGateChange: workspaceFlow.updateTeamDefaultInviteApprovalGate,
    onApplyTeamDefaultsToRoom: workspaceFlow.applyTeamDefaultsToRoom,
    roomRecords: rooms
    },
    localPreviewDialog: {
    localPreviewDialog,
    setLocalPreviewDialog,
    localPreviewBusy,
    prepareLocalPreviewConfirmation: roomRuntime.prepareLocalPreviewConfirmation,
    confirmLocalPreviewShare: roomRuntime.confirmLocalPreviewShare
    }
  });

  return <AppShellView {...appShellViewProps} />;
}
