import type {
  LocalPreviewPlaintextPayload
} from "@multaiplayer/protocol";
import {
  codexModelOptions,
  defaultBrowserProfilePersistent,
  defaultCodexModel,
} from "@multaiplayer/protocol";
import { decryptJson } from "@multaiplayer/crypto";
import { loadHistorySettings } from "./lib/localHistory";
import {
  defaultProjectPath,
  type GitWorkflowResult,
} from "./lib/localBackend";
import type { GitHubActionRun } from "./lib/authClient";
import {
  normalizeRoomName
} from "./lib/workspaceCreation";
import { attachmentReviewScopeKey } from "./lib/attachmentPolicy";
import { roomChatGateMessage } from "./lib/chatPolicy";
import type { GitHubActionsTarget } from "./lib/githubWorkflowReadiness";
import type { GitWorkflowDraft } from "./lib/gitWorkflowDraft";
import {
  embeddedAttachmentBytes,
  encodedBytes,
  attachmentTypeFromName,
  formatTimestamp
} from "./lib/appFormatters";
import { useAppStateSlices } from "./hooks/useAppStateSlices";
import { useGitHubAuth } from "./hooks/useGitHubAuth";
import { useLocalIdentity } from "./hooks/useLocalIdentity";
import { useRoomChatMutations } from "./hooks/useRoomChatMutations";
import { useAppRoomInteractionContext } from "./hooks/useAppRoomInteractionContext";
import { useAppRoomScopedSetters } from "./hooks/useAppRoomScopedSetters";
import { useAppSelectedRoomRuntime } from "./hooks/useAppSelectedRoomRuntime";
import { useAppRoomDisplayContext } from "./hooks/useAppRoomDisplayContext";
import { useThemeMode } from "./hooks/useThemeMode";
import { useAppWorkspaceRecords } from "./hooks/useAppWorkspaceRecords";
import { useHostHandoffActions } from "./hooks/useHostHandoffActions";
import { useInviteActions } from "./hooks/useInviteActions";
import { useRoomSettingsActor } from "./hooks/useRoomSettingsActor";
import { useAppRefs } from "./hooks/useAppRefs";
import { useAppSelectedRoomContext } from "./hooks/useAppSelectedRoomContext";
import { useAppViewProps } from "./hooks/useAppViewProps";
import { useWorkspaceFlowContext } from "./hooks/useWorkspaceFlowContext";
import { useRelaySyncContext } from "./hooks/useRelaySyncContext";
import { useRoomRuntimeContext } from "./hooks/useRoomRuntimeContext";
import { useRoomPanelActions } from "./hooks/useRoomPanelActions";
import { InlineSecretWarning } from "./components/common";
import { AppShellView } from "./components/AppShellView";
import type { InspectorTab } from "./components/RoomInspectorPanel";
import type {
  BrowserAccessRequest,
  ChatAttachment,
  ChatReaction,
  LocalPreviewRecord,
  NoSecretRoomInvite,
  SidebarPanel,
  TerminalCommandRequest
} from "./types";
import {
  approvalPolicyLabels,
  defaultBrowserReason,
  defaultBrowserStatus,
  defaultBrowserUrl,
  emptyRoom,
  initialMessagesByRoom,
  initialTerminalLinesByRoom,
  maxTerminalActivityLines,
  roomModeLabels,
  seededRooms,
  seededTeamMembers,
  seededTeams
} from "./seedData";

export function App() {
  const theme = useThemeMode();
  const appState = useAppStateSlices({
    workspace: {
      initialTeams: seededTeams,
      initialRooms: seededRooms,
      initialTeamMembersByTeam: seededTeamMembers,
      initialProjectPath: defaultProjectPath,
      initialRoomId: "room-desktop",
      initialMessagesByRoom
    },
    historyDefaults: { initialTeamId: seededTeams[0].id },
    terminals: { initialTerminalLinesByRoom }
  });
  const {
    workspaceState,
    appConfigState,
    roomChatState,
    roomSettingsState,
    historyDefaultsState,
    roomRuntimeState,
    codexRoomState,
    localPreviewState,
    appRuntimeState,
    terminalPanelState,
    browserPanelState,
    githubWorkflowPanelState,
    filePanelState,
    invitePanelState,
    shellLayout
  } = appState;
  const appRefs = useAppRefs({
    rooms: workspaceState.rooms,
    selectedRoomId: workspaceState.selectedRoomId,
    gitWorkflowDraftsByRoom: githubWorkflowPanelState.gitWorkflowDraftsByRoom,
    hostBusyByRoom: roomSettingsState.hostBusyByRoom,
    settingsBusyByRoom: roomSettingsState.settingsBusyByRoom,
    keyRotationBusyByRoom: invitePanelState.keyRotationBusyByRoom,
    gitWorkflowBusyByRoom: githubWorkflowPanelState.gitWorkflowBusyByRoom,
    actionsBusyByRoom: githubWorkflowPanelState.actionsBusyByRoom,
    localPreviewBusyByRoom: localPreviewState.localPreviewBusyByRoom,
    fileBusyByRoom: filePanelState.fileBusyByRoom,
    terminalBusyByRoom: terminalPanelState.terminalBusyByRoom,
    browserRequestsByRoom: browserPanelState.browserRequestsByRoom
  });
  const githubAuth = useGitHubAuth(appConfigState.appConfig.relayHttpUrl);
  const localIdentity = useLocalIdentity(githubAuth.currentUser);
  const roomSettingsActor = useRoomSettingsActor(localIdentity.localUser);

  const selectedContext = useAppSelectedRoomContext({
    appState,
    githubAuth,
    localIdentity,
    fallbackRoom: emptyRoom,
    defaultBrowserUrl,
    defaultBrowserReason
  });
  const {
    selectedCodexModel,
    hasSelectedRoom,
    selectedRoom,
    inspectorTab,
    secretWarningVisible,
    roomTerminals,
    markdownSelectionMode,
    selectedMessageIds,
    clearSelectedMessages,
    toggleMarkdownSelectionMode,
    toggleMessageSelection,
    selectedTeamName,
    selectedTeamMembersMessage,
    selectedTeamMembersBusy,
    selectedTeamMemberRows,
    customCodexModel,
    projectPathDraft,
    messages,
    draft,
    selectedMessages,
    pendingAttachments,
    pendingAttachmentBytes,
    browserRequests,
    browserUrl,
    browserReason,
    activeBrowserUrl,
    gitStatus,
    gitWorkflowDraft,
    gitWorkflowBusy,
    gitWorkflowMessage,
    actionRuns,
    actionsBusy,
    actionsLastChecked,
    actionsMessage,
    terminalLines,
    terminalBusy,
    selectedTerminalId,
    terminalName,
    terminalCommand,
    terminalInput,
    terminalError,
    fileQuery,
    projectFiles,
    selectedFile,
    selectedDiff,
    filePreviewTab,
    fileBusy,
    fileMessage,
    inviteLink,
    inviteApprovalGate,
    inviteMessage,
    hostMessage,
    chatMessage,
    settingsMessage,
    visibleHistoryMessage,
    markdownCopyFallback
  } = selectedContext;
  const roomSetters = useAppRoomScopedSetters({
    appState,
    appRefs,
    selectedRoom,
    hasSelectedRoom,
    maxTerminalActivityLines,
    defaultBrowserUrl,
    defaultBrowserReason,
    defaultCodexModel,
    defaultProjectPath
  });
  const {
    setHostMessageForRoom,
    setSelectedHostMessage,
    setChatMessageForRoom,
    setSelectedChatMessage,
    setMarkdownCopyFallbackForRoom,
    setSecretWarningVisibleForRoom,
    setHistoryMessageForRoom,
    setSelectedHistoryMessage,
    setTeamHistoryMessageForTeam,
    setSelectedTeamHistoryMessage,
    setSettingsMessageForRoom,
    setSelectedSettingsMessage,
    setGitWorkflowBusyForRoom,
    setActionsBusyForRoom,
    setLocalPreviewBusyForRoom,
    setHostBusyForRoom,
    setSettingsBusyForRoom,
    setKeyRotationBusyForRoom,
    setFileBusyForRoom,
    setTerminalBusyForRoom,
    setFileQueryForRoom,
    setProjectFilesForRoom,
    setSelectedFileForRoom,
    setSelectedDiffForRoom,
    setFilePreviewTabForRoom,
    setFileMessageForRoom,
    setSelectedFileMessage,
    resetFileContextForRoom,
    setSelectedTerminalIdForRoom,
    setTerminalNameForRoom,
    setTerminalCommandForRoom,
    setTerminalInputForRoom,
    setTerminalErrorForRoom,
    setSelectedTerminalError,
    appendTerminalLinesForRoom,
    setApprovalVisibleForRoom,
    setPendingCodexApprovalForRoom,
    resetCodexApprovalForRoom,
    setCodexRunningForRoom,
    setBrowserUrlForRoom,
    setBrowserReasonForRoom,
    setBrowserMessageForRoom,
    setSelectedBrowserMessage,
    setInviteLinkForRoom,
    setInviteApprovalGateForRoom,
    setInviteMessageForRoom,
    setSelectedInviteMessage,
    setPendingAttachmentsForRoom,
    setDraftForRoom,
    setCustomCodexModelForRoom,
    setProjectPathDraftForRoom,
    setGitWorkflowMessageForRoom,
    setSelectedGitWorkflowMessage,
    setGitStatusForRoom,
    updateSelectedGitWorkflowDraft,
    appendGitWorkflowEvent,
    appendGitHubActionsEvent,
    appendLocalPreviewEvent,
    appendHostHandoff,
    appendInviteRequest,
    appendCodexEvent,
    updateInviteRequestStatus,
    appendTerminalRequest,
    updateTerminalRequestStatus,
    appendBrowserRequest,
    updateBrowserRequestStatus
  } = roomSetters;
  const roomChatMutations = useRoomChatMutations({
    setMessagesByRoom: workspaceState.setMessagesByRoom
  });
  const workspaceRecords = useAppWorkspaceRecords({
    appState,
    appRefs,
    localIdentity,
    selected: selectedContext,
    roomSetters
  });
  const roomInteraction = useAppRoomInteractionContext({
    appState,
    appRefs,
    githubAuth,
    localIdentity,
    selected: selectedContext,
    roomChatMutations,
    roomSetters
  });
  const selectedRuntime = useAppSelectedRoomRuntime({
    appState,
    localIdentity,
    selected: selectedContext,
    roomInteraction
  });
  const hostHandoffActions = useHostHandoffActions({
    hasSelectedRoom,
    selectedRoom,
    selectedRoomIdRef: appRefs.selectedRoomIdRef,
    isSelectedRoomLocked: roomInteraction.isSelectedRoomLocked,
    isSelectedRoomRevoked: roomInteraction.isSelectedRoomRevoked,
    isActiveHost: roomInteraction.isActiveHost,
    hostGateMessage: roomInteraction.hostGateMessage,
    hostHandoffs: selectedRuntime.hostHandoffs,
    localUser: localIdentity.localUser,
    deviceId: localIdentity.deviceId,
    relayStatus: appRuntimeState.relayStatus,
    relayRef: appRefs.relayRef,
    seenEnvelopeIds: appRefs.seenEnvelopeIds,
    messages,
    terminals: terminalPanelState.terminals,
    browserRequestsByRoom: browserPanelState.browserRequestsByRoom,
    gitStatus,
    gitStatusByRoom: githubWorkflowPanelState.gitStatusByRoom,
    reportRoomHostMutationInFlight: roomInteraction.reportRoomHostMutationInFlight,
    roomSettingsActor,
    setRooms: workspaceState.setRooms,
    setCodexContinuationByRoom: roomRuntimeState.setCodexContinuationByRoom,
    setHostHandoffsByRoom: roomRuntimeState.setHostHandoffsByRoom,
    setHostBusyForRoom,
    setHostMessageForRoom,
    setSelectedHostMessage,
    setSettingsMessageForRoom,
    setProjectPathDraftForRoom,
    setCustomCodexModelForRoom,
    resetFileContextForRoom,
    resetCodexApprovalForRoom,
    appendHostHandoff
  });
  const inviteActions = useInviteActions({
    hasSelectedRoom,
    selectedRoom,
    selectedRoomIdRef: appRefs.selectedRoomIdRef,
    isSelectedRoomLocked: roomInteraction.isSelectedRoomLocked,
    isSelectedRoomRevoked: roomInteraction.isSelectedRoomRevoked,
    isActiveHost: roomInteraction.isActiveHost,
    hostGateMessage: roomInteraction.hostGateMessage,
    inviteApprovalGate,
    inviteRequests: selectedRuntime.inviteRequests,
    inviteSecretInput: invitePanelState.inviteSecretInput,
    localUser: localIdentity.localUser,
    deviceId: localIdentity.deviceId,
    deviceIdentity: appRuntimeState.deviceIdentity,
    relayStatus: appRuntimeState.relayStatus,
    relayRef: appRefs.relayRef,
    seenEnvelopeIds: appRefs.seenEnvelopeIds,
    historyLoadedRoomIds: appRefs.historyLoadedRoomIds,
    reportRoomKeyRotationInFlight: roomInteraction.reportRoomKeyRotationInFlight,
    upsertTeam: workspaceRecords.upsertTeam,
    upsertRoom: workspaceRecords.upsertRoom,
    appendInviteRequest,
    updateInviteRequestStatus,
    appendRoomMessage: roomChatMutations.appendRoomMessage,
    setSelectedInviteMessage,
    setInviteMessageForRoom,
    setInviteLinkForRoom,
    setInviteSecretInput: invitePanelState.setInviteSecretInput,
    setSelectedTeam: workspaceState.setSelectedTeam,
    setSelectedRoomId: workspaceState.setSelectedRoomId,
    setForgottenRoomIds: roomRuntimeState.setForgottenRoomIds,
    setRevokedRoomIds: roomRuntimeState.setRevokedRoomIds,
    setRevokedTeamIds: roomRuntimeState.setRevokedTeamIds,
    setInviteAdmissionsByRoom: invitePanelState.setInviteAdmissionsByRoom,
    setMessagesByRoom: workspaceState.setMessagesByRoom,
    setKeyRotationBusyForRoom
  });

  const roomDisplay = useAppRoomDisplayContext({
    appState,
    selected: selectedContext,
    selectedRuntime,
    approvalPolicyLabels
  });
  const workspaceFlow = useWorkspaceFlowContext({
    bootstrap: {
      workspace: {
        relayHttpUrl: appConfigState.appConfig.relayHttpUrl,
        setTeams: workspaceState.setTeams,
        setRooms: workspaceState.setRooms,
        setSelectedTeam: workspaceState.setSelectedTeam,
        setSelectedRoomId: workspaceState.setSelectedRoomId,
        setWorkspaceError: workspaceState.setWorkspaceError
      },
      selectedRoomReadReceipt: {
        selectedRoomId: workspaceState.selectedRoomId,
        setRooms: workspaceState.setRooms
      },
      deviceIdentity: {
        relayHttpUrl: appConfigState.appConfig.relayHttpUrl,
        deviceId: localIdentity.deviceId,
        userId: localIdentity.localUser.id,
        displayName: localIdentity.localUser.name,
        deviceIdentity: appRuntimeState.deviceIdentity,
        setDeviceIdentity: appRuntimeState.setDeviceIdentity,
        setDeviceIdentityMessage: appRuntimeState.setDeviceIdentityMessage
      },
      selectedTeamDefaults: {
        selectedTeam: workspaceState.selectedTeam,
        setTeamHistorySettings: historyDefaultsState.setTeamHistorySettings,
        setTeamDefaultApprovalPolicy: historyDefaultsState.setTeamDefaultApprovalPolicy,
        setTeamDefaultCodexModel: historyDefaultsState.setTeamDefaultCodexModel,
        setTeamDefaultBrowserProfilePersistent: historyDefaultsState.setTeamDefaultBrowserProfilePersistent,
        setTeamDefaultInviteApprovalGate: historyDefaultsState.setTeamDefaultInviteApprovalGate
      },
      inviteUrl: {
        requestNoSecretInviteAccess: inviteActions.requestNoSecretInviteAccess,
        acceptInvite: inviteActions.acceptInvite,
        setSelectedInviteMessage
      }
    },
    markdownCopy: {
      hasSelectedRoom,
      canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
      localWorkspaceMessage: roomInteraction.localWorkspaceMessage,
      selectedRoom,
      teams: workspaceState.teams,
      messages,
      selectedMessages,
      gitStatus,
      selectedFile,
      selectedDiff,
      selectedFileRisks: roomDisplay.selectedFileRisks,
      selectedTerminal: selectedRuntime.selectedTerminal,
      terminalLines,
      terminalRisks: roomDisplay.terminalRisks,
      setMarkdownCopyFallbackForRoom,
      setSelectedChatMessage,
      setChatMessageForRoom,
      setSelectedFileMessage,
      setFileMessageForRoom,
      setSelectedTerminalError,
      setTerminalErrorForRoom,
      setSelectedGitWorkflowMessage,
      setGitWorkflowMessageForRoom
    },
    workspaceRoomActions: {
      members: {
        selectedTeam: workspaceState.selectedTeam,
        selectedTeamName,
        selectedTeamMembersBusy,
        selectedRoom,
        localUser: localIdentity.localUser,
        currentUser: githubAuth.currentUser,
        setDeviceIdentityMessage: appRuntimeState.setDeviceIdentityMessage,
        setTrustedDeviceKeys: appRuntimeState.setTrustedDeviceKeys,
        setTeamMembersBusyByTeam: workspaceState.setTeamMembersBusyByTeam,
        setTeamMembersMessageByTeam: workspaceState.setTeamMembersMessageByTeam,
        setTeamMembersByTeam: workspaceState.setTeamMembersByTeam,
        setTeams: workspaceState.setTeams
      },
      workspaceCreation: {
        selectedTeam: workspaceState.selectedTeam,
        newTeamName: workspaceState.newTeamName,
        newRoomName: workspaceState.newRoomName,
        newRoomProjectPath: workspaceState.newRoomProjectPath,
        setWorkspaceError: workspaceState.setWorkspaceError,
        setSelectedTeam: workspaceState.setSelectedTeam,
        setSelectedRoomId: workspaceState.setSelectedRoomId,
        setNewTeamName: workspaceState.setNewTeamName,
        setNewRoomName: workspaceState.setNewRoomName,
        setNewRoomProjectPath: workspaceState.setNewRoomProjectPath,
        setRevokedRoomIds: roomRuntimeState.setRevokedRoomIds,
        setRevokedTeamIds: roomRuntimeState.setRevokedTeamIds,
        setForgottenRoomIds: roomRuntimeState.setForgottenRoomIds,
        setMessagesByRoom: workspaceState.setMessagesByRoom,
        setInviteApprovalGateForRoom,
        upsertTeam: workspaceRecords.upsertTeam,
        upsertRoom: workspaceRecords.upsertRoom
      },
      teamDefaults: {
        selectedTeam: workspaceState.selectedTeam,
        approvalPolicyLabels,
        setSelectedTeamHistoryMessage,
        setTeamHistoryMessageForTeam,
        setTeamHistorySettings: historyDefaultsState.setTeamHistorySettings,
        setTeamDefaultApprovalPolicy: historyDefaultsState.setTeamDefaultApprovalPolicy,
        setTeamDefaultCodexModel: historyDefaultsState.setTeamDefaultCodexModel,
        setTeamDefaultBrowserProfilePersistent: historyDefaultsState.setTeamDefaultBrowserProfilePersistent,
        setTeamDefaultInviteApprovalGate: historyDefaultsState.setTeamDefaultInviteApprovalGate
      },
      localHistory: {
        hasSelectedRoom,
        selectedRoom,
        selectedRoomIdRef: appRefs.selectedRoomIdRef,
        isSelectedRoomLocked: roomInteraction.isSelectedRoomLocked,
        isSelectedRoomRevoked: roomInteraction.isSelectedRoomRevoked,
        isActiveHost: roomInteraction.isActiveHost,
        messages,
        terminalRequests: selectedRuntime.terminalRequests,
        browserRequests,
        inviteRequests: selectedRuntime.inviteRequests,
        codexEvents: selectedRuntime.codexEvents,
        gitWorkflowEvents: selectedRuntime.gitWorkflowEvents,
        githubActionsEvents: selectedRuntime.githubActionsEvents,
        localPreviews: selectedRuntime.localPreviews,
        terminals: terminalPanelState.terminals,
        hostHandoffs: selectedRuntime.hostHandoffs,
        selectedCodexThreadId: selectedRuntime.selectedCodexThreadId,
        reportRoomSettingsMutationInFlight: roomInteraction.reportRoomSettingsMutationInFlight,
        roomSettingsActor,
        setSelectedHistoryMessage,
        setHistoryMessageForRoom,
        setInviteApprovalGateForRoom,
        setSettingsBusyForRoom,
        setSecretWarningVisibleForRoom,
        setHistorySettings: historyDefaultsState.setHistorySettings,
        setMessagesByRoom: workspaceState.setMessagesByRoom,
        setTerminalRequestsByRoom: terminalPanelState.setTerminalRequestsByRoom,
        setBrowserRequestsByRoom: browserPanelState.setBrowserRequestsByRoom,
        setInviteRequestsByRoom: invitePanelState.setInviteRequestsByRoom,
        setCodexEventsByRoom: codexRoomState.setCodexEventsByRoom,
        setGitWorkflowEventsByRoom: roomRuntimeState.setGitWorkflowEventsByRoom,
        setGitHubActionsEventsByRoom: roomRuntimeState.setGitHubActionsEventsByRoom,
        setLocalPreviewsByRoom: localPreviewState.setLocalPreviewsByRoom,
        setTerminals: terminalPanelState.setTerminals,
        setHostHandoffsByRoom: roomRuntimeState.setHostHandoffsByRoom,
        setRooms: workspaceState.setRooms,
        setBrowserStatusByRoom: browserPanelState.setBrowserStatusByRoom,
        setActiveBrowserUrlsByRoom: browserPanelState.setActiveBrowserUrlsByRoom,
        setCodexThreadIdsByRoom: codexRoomState.setCodexThreadIdsByRoom,
        setActionRunsByRoom: githubWorkflowPanelState.setActionRunsByRoom,
        setActionsLastCheckedByRoom: githubWorkflowPanelState.setActionsLastCheckedByRoom,
        setActionsMessagesByRoom: githubWorkflowPanelState.setActionsMessagesByRoom,
        setActionsBusyByRoom: githubWorkflowPanelState.setActionsBusyByRoom,
        setGitWorkflowBusyByRoom: githubWorkflowPanelState.setGitWorkflowBusyByRoom,
        setHostBusyByRoom: roomSettingsState.setHostBusyByRoom,
        setHostMessagesByRoom: roomSettingsState.setHostMessagesByRoom,
        setChatMessagesByRoom: roomChatState.setChatMessagesByRoom,
        setMarkdownCopyFallbacksByRoom: filePanelState.setMarkdownCopyFallbacksByRoom,
        setSecretWarningsVisibleByRoom: codexRoomState.setSecretWarningsVisibleByRoom,
        setHistoryMessagesByRoom: historyDefaultsState.setHistoryMessagesByRoom,
        setSettingsBusyByRoom: roomSettingsState.setSettingsBusyByRoom,
        setSettingsMessagesByRoom: roomSettingsState.setSettingsMessagesByRoom,
        setCustomCodexModelsByRoom: roomSettingsState.setCustomCodexModelsByRoom,
        setProjectPathDraftsByRoom: roomSettingsState.setProjectPathDraftsByRoom,
        setKeyRotationBusyByRoom: invitePanelState.setKeyRotationBusyByRoom,
        setApprovalVisibleByRoom: codexRoomState.setApprovalVisibleByRoom,
        setPendingCodexApprovalsByRoom: codexRoomState.setPendingCodexApprovalsByRoom,
        setCodexRunningByRoom: codexRoomState.setCodexRunningByRoom,
        setGitStatusByRoom: githubWorkflowPanelState.setGitStatusByRoom,
        setFileQueriesByRoom: filePanelState.setFileQueriesByRoom,
        setProjectFilesByRoom: filePanelState.setProjectFilesByRoom,
        setSelectedFilesByRoom: filePanelState.setSelectedFilesByRoom,
        setSelectedDiffsByRoom: filePanelState.setSelectedDiffsByRoom,
        setFileBusyByRoom: filePanelState.setFileBusyByRoom,
        setFileMessagesByRoom: filePanelState.setFileMessagesByRoom,
        setPendingAttachmentsByRoom: roomChatState.setPendingAttachmentsByRoom,
        setTerminalLinesByRoom: terminalPanelState.setTerminalLinesByRoom,
        setTerminalBusyByRoom: terminalPanelState.setTerminalBusyByRoom,
        setSelectedTerminalIdsByRoom: terminalPanelState.setSelectedTerminalIdsByRoom,
        setTerminalNamesByRoom: terminalPanelState.setTerminalNamesByRoom,
        setTerminalCommandsByRoom: terminalPanelState.setTerminalCommandsByRoom,
        setTerminalInputsByRoom: terminalPanelState.setTerminalInputsByRoom,
        setTerminalErrorsByRoom: terminalPanelState.setTerminalErrorsByRoom,
        setBrowserUrlsByRoom: browserPanelState.setBrowserUrlsByRoom,
        setBrowserReasonsByRoom: browserPanelState.setBrowserReasonsByRoom,
        setBrowserMessagesByRoom: browserPanelState.setBrowserMessagesByRoom,
        setInviteLinksByRoom: invitePanelState.setInviteLinksByRoom,
        setInviteApprovalGatesByRoom: invitePanelState.setInviteApprovalGatesByRoom,
        setInviteMessagesByRoom: invitePanelState.setInviteMessagesByRoom,
        setDraftsByRoom: roomChatState.setDraftsByRoom,
        setForgottenRoomIds: roomRuntimeState.setForgottenRoomIds,
        historyLoadedRoomIds: appRefs.historyLoadedRoomIds
      },
      files: {
        hasSelectedRoom,
        canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
        localWorkspaceMessage: roomInteraction.localWorkspaceMessage,
        selectedRoom,
        selectedRoomIdRef: appRefs.selectedRoomIdRef,
        isSelectedRoomLocked: roomInteraction.isSelectedRoomLocked,
        isSelectedRoomRevoked: roomInteraction.isSelectedRoomRevoked,
        selectedFile,
        pendingAttachmentsByRoom: roomChatState.pendingAttachmentsByRoom,
        sensitiveAttachmentReviewKey: roomChatState.sensitiveAttachmentReviewKey,
        setSensitiveAttachmentReviewKey: roomChatState.setSensitiveAttachmentReviewKey,
        reportRoomFileActionInFlight: roomInteraction.reportRoomFileActionInFlight,
        setFileBusyForRoom,
        setSelectedFileForRoom,
        setSelectedDiffForRoom,
        setFilePreviewTabForRoom,
        setSelectedFileMessage,
        setFileMessageForRoom,
        setPendingAttachmentsForRoom,
        setInspectorTabsByRoom: roomRuntimeState.setInspectorTabsByRoom
      }
    },
    historyEffects: {
    hydration: {
      hasSelectedRoom,
      selectedRoomId: workspaceState.selectedRoomId,
      selectedRoomTeamId: selectedRoom.teamId,
      forgottenRoomIds: roomRuntimeState.forgottenRoomIds,
      historyLoadedRoomIds: appRefs.historyLoadedRoomIds,
      setHistorySettings: historyDefaultsState.setHistorySettings,
      setMessagesByRoom: workspaceState.setMessagesByRoom,
      setTerminalRequestsByRoom: terminalPanelState.setTerminalRequestsByRoom,
      setBrowserRequestsByRoom: browserPanelState.setBrowserRequestsByRoom,
      setInviteRequestsByRoom: invitePanelState.setInviteRequestsByRoom,
      setCodexEventsByRoom: codexRoomState.setCodexEventsByRoom,
      setGitWorkflowEventsByRoom: roomRuntimeState.setGitWorkflowEventsByRoom,
      setGitHubActionsEventsByRoom: roomRuntimeState.setGitHubActionsEventsByRoom,
      setLocalPreviewsByRoom: localPreviewState.setLocalPreviewsByRoom,
      setGitWorkflowMessageForRoom,
      setActionRunsByRoom: githubWorkflowPanelState.setActionRunsByRoom,
      setActionsLastCheckedByRoom: githubWorkflowPanelState.setActionsLastCheckedByRoom,
      setActionsMessagesByRoom: githubWorkflowPanelState.setActionsMessagesByRoom,
      setTerminals: terminalPanelState.setTerminals,
      setSelectedTerminalIdsByRoom: terminalPanelState.setSelectedTerminalIdsByRoom,
      setHostHandoffsByRoom: roomRuntimeState.setHostHandoffsByRoom,
      setCodexThreadIdsByRoom: codexRoomState.setCodexThreadIdsByRoom
    },
    search: {
      searchActive: roomDisplay.searchActive,
      rooms: workspaceState.rooms,
      forgottenRoomIds: roomRuntimeState.forgottenRoomIds,
      revokedRoomIds: roomRuntimeState.revokedRoomIds,
      revokedTeamIds: roomRuntimeState.revokedTeamIds,
      setHistorySearchMessagesByRoom: appRuntimeState.setHistorySearchMessagesByRoom,
      setHistorySearchBusy: appRuntimeState.setHistorySearchBusy
    }
    }
  });

  const relaySync = useRelaySyncContext({
    browserOpenCommand: {
      localUser: localIdentity.localUser,
      selectedRoomIdRef: appRefs.selectedRoomIdRef,
      forgottenRoomIds: roomRuntimeState.forgottenRoomIds,
      revokedRoomIds: roomRuntimeState.revokedRoomIds,
      revokedTeamIds: roomRuntimeState.revokedTeamIds,
      appendBrowserRequest,
      setBrowserMessageForRoom,
      setBrowserUrlForRoom,
      setActiveBrowserUrlsByRoom: browserPanelState.setActiveBrowserUrlsByRoom,
      setBrowserStatusByRoom: browserPanelState.setBrowserStatusByRoom,
      setInspectorTabsByRoom: roomRuntimeState.setInspectorTabsByRoom
    },
    relayRoomSync: {
      subscription: {
        relayWsUrl: appConfigState.appConfig.relayWsUrl,
        deviceId: localIdentity.deviceId,
        localUser: localIdentity.localUser,
        devicePublicKeyFingerprint: appRuntimeState.deviceIdentity?.publicKeyFingerprint,
        selectedTeam: workspaceState.selectedTeam,
        selectedRoom,
        hasSelectedRoom,
        isActiveHost: roomInteraction.isActiveHost,
        inviteAdmissionsByRoom: invitePanelState.inviteAdmissionsByRoom,
        revokedRoomIds: roomRuntimeState.revokedRoomIds,
        revokedTeamIds: roomRuntimeState.revokedTeamIds,
        approvalPolicyLabels,
        roomModeLabels,
        relayRef: appRefs.relayRef,
        seenEnvelopeIds: appRefs.seenEnvelopeIds,
        roomsRef: appRefs.roomsRef,
        selectedRoomIdRef: appRefs.selectedRoomIdRef,
        historyLoadedRoomIds: appRefs.historyLoadedRoomIds,
        setRelayStatus: appRuntimeState.setRelayStatus,
        setPresenceByRoom: roomRuntimeState.setPresenceByRoom,
        setRooms: workspaceState.setRooms,
        setMessagesByRoom: workspaceState.setMessagesByRoom,
        setTerminalRequestsByRoom: terminalPanelState.setTerminalRequestsByRoom,
        setBrowserRequestsByRoom: browserPanelState.setBrowserRequestsByRoom,
        setActionRunsByRoom: githubWorkflowPanelState.setActionRunsByRoom,
        setActionsLastCheckedByRoom: githubWorkflowPanelState.setActionsLastCheckedByRoom,
        setActionsMessagesByRoom: githubWorkflowPanelState.setActionsMessagesByRoom,
        setForgottenRoomIds: roomRuntimeState.setForgottenRoomIds,
        handleRelayError: workspaceRecords.handleRelayError,
        upsertRoom: workspaceRecords.upsertRoom,
        upsertTeam: workspaceRecords.upsertTeam,
        refreshTeamMembers: roomDisplay.refreshTeamMembers,
        decryptInviteEnvelope: inviteActions.decryptInviteEnvelope,
        handleInviteEnvelopePlaintext: inviteActions.handleInviteEnvelopePlaintext,
        applyMessageReaction: roomChatMutations.applyMessageReaction,
        updateTerminalRequestStatus,
        appendTerminalLinesForRoom,
        appendGitWorkflowEvent,
        setGitWorkflowMessageForRoom,
        appendGitHubActionsEvent,
        appendCodexEvent,
        updateBrowserRequestStatus,
        appendLocalPreviewEvent,
        setChatMessageForRoom,
        markHostHandoffAccepted: hostHandoffActions.markHostHandoffAccepted,
        setHostMessageForRoom,
        appendHostHandoff,
        appendRoomMessage: roomChatMutations.appendRoomMessage,
        setInviteMessageForRoom
      },
      publishers: {
        relayRef: appRefs.relayRef,
        seenEnvelopeIds: appRefs.seenEnvelopeIds,
        relayStatus: appRuntimeState.relayStatus,
        selectedRoom,
        deviceId: localIdentity.deviceId,
        localUser: localIdentity.localUser,
        approvalPolicyLabels,
        roomModeLabels,
        appendLocalPreviewEvent,
        appendGitWorkflowEvent,
        appendCodexEvent,
        appendTerminalLinesForRoom,
        appendRoomMessage: roomChatMutations.appendRoomMessage,
        appendGitHubActionsEvent
      }
    }
  });
  const roomRuntime = useRoomRuntimeContext({
    codexActions: {
      turn: {
      selectedRoom,
      activeCodexApproval: selectedRuntime.activeCodexApproval,
      roomsRef: appRefs.roomsRef,
      selectedRoomIdRef: appRefs.selectedRoomIdRef,
      forgottenRoomIds: roomRuntimeState.forgottenRoomIds,
      revokedRoomIds: roomRuntimeState.revokedRoomIds,
      revokedTeamIds: roomRuntimeState.revokedTeamIds,
      localUser: localIdentity.localUser,
      messagesByRoom: workspaceState.messagesByRoom,
      terminals: terminalPanelState.terminals,
      browserRequestsByRoom: browserPanelState.browserRequestsByRoom,
      gitStatusByRoom: githubWorkflowPanelState.gitStatusByRoom,
      codexContinuationByRoom: roomRuntimeState.codexContinuationByRoom,
      codexThreadIdsByRoom: codexRoomState.codexThreadIdsByRoom,
      setHostMessageForRoom,
      setPendingCodexApprovalForRoom,
      setApprovalVisibleForRoom,
      setCodexRunningForRoom,
      appendTerminalLinesForRoom,
      setCodexThreadIdsByRoom: codexRoomState.setCodexThreadIdsByRoom,
      setCodexContinuationByRoom: roomRuntimeState.setCodexContinuationByRoom,
      setRooms: workspaceState.setRooms,
      publishCodexEvent: relaySync.publishCodexEvent,
      publishChatMessage: roomInteraction.publishChatMessage,
      publishHostHandoff: hostHandoffActions.publishHostHandoff
    },
      invoke: {
      hasSelectedRoom,
      selectedRoom,
      selectedRoomIdRef: appRefs.selectedRoomIdRef,
      isSelectedRoomLocked: roomInteraction.isSelectedRoomLocked,
      isSelectedRoomRevoked: roomInteraction.isSelectedRoomRevoked,
      isActiveHost: roomInteraction.isActiveHost,
      canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
      hostGateMessage: roomInteraction.hostGateMessage,
      localUser: localIdentity.localUser,
      draft,
      pendingAttachments,
      messages,
      roomTerminals,
      browserRequests,
      gitStatus,
      publishChatMessage: roomInteraction.publishChatMessage,
      handleCodexBrowserOpenCommand: relaySync.handleCodexBrowserOpenCommand,
      setSelectedChatMessage,
      setChatMessageForRoom,
      setSelectedHostMessage,
      setHostMessageForRoom,
      setPendingCodexApprovalForRoom,
      setApprovalVisibleForRoom,
      setDraftForRoom,
      setPendingAttachmentsForRoom
      }
    },
    toolActions: {
      settings: {
      hasSelectedRoom,
      isSelectedRoomLocked: roomInteraction.isSelectedRoomLocked,
      isSelectedRoomRevoked: roomInteraction.isSelectedRoomRevoked,
      isActiveHost: roomInteraction.isActiveHost,
      selectedRoom,
      selectedRoomIdRef: appRefs.selectedRoomIdRef,
      selectedCodexModel,
      projectPathDraft,
      approvalPolicyLabels,
      roomModeLabels,
      roomSettingsGateMessage: roomInteraction.roomSettingsGateMessage,
      roomSettingsActor,
      reportRoomSettingsMutationInFlight: roomInteraction.reportRoomSettingsMutationInFlight,
      setSettingsBusyForRoom,
      setSelectedSettingsMessage,
      setSettingsMessageForRoom,
      setSelectedBrowserMessage,
      setBrowserMessageForRoom,
      setRooms: workspaceState.setRooms,
      setBrowserStatusByRoom: browserPanelState.setBrowserStatusByRoom,
      setProjectPathDraftForRoom,
      resetCodexApprovalForRoom,
      resetFileContextForRoom,
      publishRoomSettingsEvent: relaySync.publishRoomSettingsEvent
    },
    terminal: {
      hasSelectedRoom,
      isActiveHost: roomInteraction.isActiveHost,
      canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
      canRequestWorkspace: roomInteraction.canRequestWorkspace,
      hostGateMessage: roomInteraction.hostGateMessage,
      localWorkspaceMessage: roomInteraction.localWorkspaceMessage,
      workspaceRequestMessage: roomInteraction.workspaceRequestMessage,
      selectedRoom,
      selectedRoomIdRef: appRefs.selectedRoomIdRef,
      isSelectedRoomLocked: roomInteraction.isSelectedRoomLocked,
      localUser: localIdentity.localUser,
      deviceId: localIdentity.deviceId,
      relayStatus: appRuntimeState.relayStatus,
      relayRef: appRefs.relayRef,
      seenEnvelopeIds: appRefs.seenEnvelopeIds,
      roomTerminals,
      selectedTerminal: selectedRuntime.selectedTerminal,
      terminalName,
      terminalCommand,
      terminalInput,
      terminalRequests: selectedRuntime.terminalRequests,
      reportRoomTerminalActionInFlight: roomInteraction.reportRoomTerminalActionInFlight,
      setTerminalBusyForRoom,
      setSelectedTerminalError,
      setTerminalErrorForRoom,
      appendTerminalLinesForRoom,
      setGitStatusForRoom,
      setTerminals: terminalPanelState.setTerminals,
      setSelectedTerminalIdForRoom,
      setTerminalNameForRoom,
      setTerminalCommandForRoom,
      setTerminalInputForRoom,
      appendTerminalRequest,
      updateTerminalRequestStatus,
      publishRequestStatus: relaySync.publishRequestStatus,
      publishTerminalResult: relaySync.publishTerminalResult
    },
    localPreview: {
      hasSelectedRoom,
      isSelectedRoomLocked: roomInteraction.isSelectedRoomLocked,
      isSelectedRoomRevoked: roomInteraction.isSelectedRoomRevoked,
      selectedRoom,
      rooms: workspaceState.rooms,
      localUser: localIdentity.localUser,
      localPreviewDialog: localPreviewState.localPreviewDialog,
      localPreviewsByRoom: localPreviewState.localPreviewsByRoom,
      setLocalPreviewDialog: localPreviewState.setLocalPreviewDialog,
      setLocalPreviewBusyForRoom,
      setSelectedChatMessage,
      setChatMessageForRoom,
      publishLocalPreviewEvent: relaySync.publishLocalPreviewEvent
    },
    account: {
      selectedRoomId: selectedRoom.id,
      deviceId: localIdentity.deviceId,
      signOutGitHub: githubAuth.signOutGitHub,
      setDeviceIdentity: appRuntimeState.setDeviceIdentity,
      setDeviceIdentityMessage: appRuntimeState.setDeviceIdentityMessage,
      setTrustedDeviceKeys: appRuntimeState.setTrustedDeviceKeys
    },
    githubActions: {
      hasSelectedRoom,
      selectedRoom,
      roomsRef: appRefs.roomsRef,
      actionsBusyRef: appRefs.actionsBusyRef,
      gitWorkflowDraftsRef: appRefs.gitWorkflowDraftsRef,
      forgottenRoomIds: roomRuntimeState.forgottenRoomIds,
      revokedRoomIds: roomRuntimeState.revokedRoomIds,
      revokedTeamIds: roomRuntimeState.revokedTeamIds,
      localUser: localIdentity.localUser,
      authConfig: githubAuth.authConfig,
      currentUser: githubAuth.currentUser,
      setActionsBusyForRoom,
      setActionsMessagesByRoom: githubWorkflowPanelState.setActionsMessagesByRoom,
      setActionRunsByRoom: githubWorkflowPanelState.setActionRunsByRoom,
      setActionsLastCheckedByRoom: githubWorkflowPanelState.setActionsLastCheckedByRoom,
      publishGitHubActionsEvent: relaySync.publishGitHubActionsEvent
    },
    gitWorkflow: {
      hasSelectedRoom,
      isActiveHost: roomInteraction.isActiveHost,
      canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
      hostGateMessage: roomInteraction.hostGateMessage,
      localWorkspaceMessage: roomInteraction.localWorkspaceMessage,
      selectedRoom,
      gitWorkflowBusyRef: appRefs.gitWorkflowBusyRef,
      gitWorkflowDraft,
      gitApprovalPreview: roomInteraction.gitApprovalPreview,
      githubWorkflowReadiness: roomInteraction.githubWorkflowReadiness,
      messages,
      gitStatus,
      setSelectedGitWorkflowMessage,
      setGitWorkflowMessageForRoom,
      setGitWorkflowBusyForRoom,
      appendTerminalLinesForRoom,
      setGitStatusForRoom,
      publishGitWorkflowEvent: relaySync.publishGitWorkflowEvent
    },
    browser: {
      hasSelectedRoom,
      isActiveHost: roomInteraction.isActiveHost,
      canRequestBrowser: roomInteraction.canRequestBrowser,
      canHostBrowser: roomInteraction.canHostBrowser,
      browserAccessMessage: roomInteraction.browserAccessMessage,
      hostGateMessage: roomInteraction.hostGateMessage,
      selectedRoom,
      selectedRoomIdRef: appRefs.selectedRoomIdRef,
      browserUrl,
      browserReason,
      browserRequests,
      localUser: localIdentity.localUser,
      deviceId: localIdentity.deviceId,
      relayStatus: appRuntimeState.relayStatus,
      relayRef: appRefs.relayRef,
      seenEnvelopeIds: appRefs.seenEnvelopeIds,
      defaultBrowserStatus,
      setSelectedBrowserMessage,
      setBrowserMessageForRoom,
      setBrowserUrlForRoom,
      appendBrowserRequest,
      updateBrowserRequestStatus,
      publishRequestStatus: relaySync.publishRequestStatus,
      setActiveBrowserUrlsByRoom: browserPanelState.setActiveBrowserUrlsByRoom,
      setBrowserStatusByRoom: browserPanelState.setBrowserStatusByRoom,
      setInspectorTabsByRoom: roomRuntimeState.setInspectorTabsByRoom
      }
    },
    backgroundEffects: {
      localHistoryPersistence: {
      hasSelectedRoom,
      selectedRoomId: workspaceState.selectedRoomId,
      selectedRoomTeamId: selectedRoom.teamId,
      forgottenRoomIds: roomRuntimeState.forgottenRoomIds,
      revokedRoomIds: roomRuntimeState.revokedRoomIds,
      revokedTeamIds: roomRuntimeState.revokedTeamIds,
      historyLoadedRoomIds: appRefs.historyLoadedRoomIds,
      historySettings: historyDefaultsState.historySettings,
      messages,
      terminalRequests: selectedRuntime.terminalRequests,
      browserRequests,
      inviteRequests: selectedRuntime.inviteRequests,
      codexEvents: selectedRuntime.codexEvents,
      gitWorkflowEvents: selectedRuntime.gitWorkflowEvents,
      githubActionsEvents: selectedRuntime.githubActionsEvents,
      localPreviews: selectedRuntime.localPreviews,
      terminals: terminalPanelState.terminals,
      hostHandoffs: selectedRuntime.hostHandoffs,
      selectedCodexThreadId: selectedRuntime.selectedCodexThreadId
    },
    localPreviewPolling: {
      localPreviewsByRoom: localPreviewState.localPreviewsByRoom,
      localUserId: localIdentity.localUser.id,
      roomsRef: appRefs.roomsRef,
      publishLocalPreviewEvent: relaySync.publishLocalPreviewEvent
    },
    roomGitStatusRefresh: {
      hasSelectedRoom,
      canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
      selectedRoomId: selectedRoom.id,
      selectedRoomProjectPath: selectedRoom.projectPath,
      setGitStatusForRoom
    },
    gitHubRemoteInference: {
      hasSelectedRoom,
      canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
      selectedRoomId: selectedRoom.id,
      selectedRoomProjectPath: selectedRoom.projectPath,
      selectedRoomIdRef: appRefs.selectedRoomIdRef,
      gitWorkflowDraftsRef: appRefs.gitWorkflowDraftsRef,
      setGitWorkflowDraftsByRoom: githubWorkflowPanelState.setGitWorkflowDraftsByRoom,
      setGitWorkflowMessageForRoom
    },
    gitHubActionsDraftReset: {
      hasSelectedRoom,
      selectedRoomId: selectedRoom.id,
      gitWorkflowDraft,
      setActionRunsByRoom: githubWorkflowPanelState.setActionRunsByRoom,
      setActionsLastCheckedByRoom: githubWorkflowPanelState.setActionsLastCheckedByRoom,
      setActionsMessagesByRoom: githubWorkflowPanelState.setActionsMessagesByRoom,
      setActionsBusyByRoom: githubWorkflowPanelState.setActionsBusyByRoom
    },
    projectFilesSearch: {
      hasSelectedRoom,
      canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
      selectedRoomId: selectedRoom.id,
      selectedRoomProjectPath: selectedRoom.projectPath,
      fileQueriesByRoom: filePanelState.fileQueriesByRoom,
      localWorkspaceMessage: roomInteraction.localWorkspaceMessage,
      setProjectFilesForRoom,
      setSelectedFileForRoom,
      setSelectedDiffForRoom,
      setFileBusyForRoom,
      setFileMessageForRoom
    },
    terminalLifecycle: {
      hasSelectedRoom,
      canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
      selectedRoomId: selectedRoom.id,
      selectedTerminalId,
      selectedTerminalRunning: selectedRuntime.selectedTerminal?.running,
      setTerminals: terminalPanelState.setTerminals,
      setSelectedTerminalIdsByRoom: terminalPanelState.setSelectedTerminalIdsByRoom,
      setSelectedTerminalIdForRoom,
      setTerminalErrorForRoom
    },
    terminalAutoOpen: {
      inspectorTab,
      hasSelectedRoom,
      isActiveHost: roomInteraction.isActiveHost,
      canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
      isSelectedRoomLocked: roomInteraction.isSelectedRoomLocked,
      terminalBusy,
      roomTerminalCount: roomTerminals.length,
      selectedRoomId: selectedRoom.id,
      terminalAutoOpenedRoomsRef: terminalPanelState.terminalAutoOpenedRoomsRef
    },
    codexProbe: { setCodexProbe: appRuntimeState.setCodexProbe },
    roomDraftCleanup: {
      hasSelectedRoom,
      selectedRoomId: selectedRoom.id,
      selectedRoomProjectPath: selectedRoom.projectPath,
      selectedCodexModel,
      setCustomCodexModelsByRoom: roomSettingsState.setCustomCodexModelsByRoom,
      setProjectPathDraftsByRoom: roomSettingsState.setProjectPathDraftsByRoom
      }
    }
  });

  const roomPanels = useRoomPanelActions({
    chat: {
      selectedRoomId: selectedRoom.id,
      messages,
      localPreviews: selectedRuntime.localPreviews,
      copyMessageMarkdown: workspaceFlow.copyMessageMarkdown,
      copyCodexOutputMarkdown: workspaceFlow.copyCodexOutputMarkdown,
      openEncryptedAttachmentBlob: workspaceFlow.openEncryptedAttachmentBlob,
      toggleMessageReaction: roomInteraction.toggleMessageReaction,
      setPendingCodexApprovalForRoom,
      setApprovalVisibleForRoom,
      approveCodexTurn: roomRuntime.approveCodexTurn,
      handleCodexInvoke: roomRuntime.handleCodexInvoke,
      copyMarkdownWithFallback: workspaceFlow.copyMarkdownWithFallback,
      setChatMessageForRoom,
      stopLocalPreview: roomRuntime.stopLocalPreview,
      setDraftForRoom
    },
    header: {
      rooms: workspaceState.rooms,
      selectedRoomId: workspaceState.selectedRoomId,
      selectedRoomIdForTabs: selectedRoom.id,
      activeBrowserUrl,
      setSelectedTeam: workspaceState.setSelectedTeam,
      setSelectedRoomId: workspaceState.setSelectedRoomId,
      setInspectorTabsByRoom: roomRuntimeState.setInspectorTabsByRoom,
      openRoomBrowserNow: roomRuntime.openRoomBrowserNow
    },
    terminal: {
      selectedRoomId: selectedRoom.id,
      terminalRequests: selectedRuntime.terminalRequests,
      copyTerminalMarkdown: workspaceFlow.copyTerminalMarkdown,
      runApprovedTerminalCheck: roomRuntime.runApprovedTerminalCheck,
      openInteractiveTerminal: roomRuntime.openInteractiveTerminal,
      setTerminalNameForRoom,
      setTerminalCommandForRoom,
      startNamedTerminal: roomRuntime.startNamedTerminal,
      requestTerminalCommand: roomRuntime.requestTerminalCommand,
      approveTerminalRequest: roomRuntime.approveTerminalRequest,
      denyTerminalRequest: roomRuntime.denyTerminalRequest,
      setSelectedTerminalIdForRoom,
      setTerminalInputForRoom,
      sendTerminalInput: roomRuntime.sendTerminalInput,
      restartSelectedTerminal: roomRuntime.restartSelectedTerminal,
      stopSelectedTerminal: roomRuntime.stopSelectedTerminal
    },
    workspaceFiles: {
      selectedRoomId: selectedRoom.id,
      copyProjectMarkdown: workspaceFlow.copyProjectMarkdown,
      setFileQueryForRoom,
      openProjectFile: workspaceFlow.openProjectFile,
      copyDiffSummaryMarkdown: workspaceFlow.copyDiffSummaryMarkdown,
      attachSelectedFileToMessage: workspaceFlow.attachSelectedFileToMessage,
      setFilePreviewTabForRoom,
      setSelectedFileForRoom,
      setSelectedDiffForRoom,
      setSensitiveAttachmentReviewKey: roomChatState.setSensitiveAttachmentReviewKey
    }
  });
  const appView = useAppViewProps({
    shell: {
      sidebarCollapsed: shellLayout.sidebarCollapsed,
      inspectorCollapsed: shellLayout.inspectorCollapsed,
      shellStyle: shellLayout.shellStyle,
      onBeginSidebarResize: (event) => shellLayout.beginShellResize("sidebar", event),
      onBeginInspectorResize: (event) => shellLayout.beginShellResize("inspector", event),
      onToggleSidebarCollapsed: shellLayout.toggleSidebarCollapsed,
      onToggleInspectorCollapsed: shellLayout.toggleInspectorCollapsed
    },
    roomMainColumn: {
    teamRecords: workspaceState.teams,
    selectedTeam: workspaceState.selectedTeam,
    selectedRoom,
    localUser: localIdentity.localUser,
    hostBusy: selectedRuntime.hostBusy,
    isActiveHost: roomInteraction.isActiveHost,
    isSelectedRoomLocked: roomInteraction.isSelectedRoomLocked,
    isSelectedRoomRevoked: roomInteraction.isSelectedRoomRevoked,
    hasSelectedRoom,
    selectedCodexModel,
    modelOptions: codexModelOptions,
    settingsBusy: selectedRuntime.settingsBusy,
    selectedMessages,
    markdownSelectionMode,
    inspectorTab,
    roomHeaderActions: roomPanels.roomHeaderActions,
    onSetHost: hostHandoffActions.setRoomHost,
    onRenameRoom: roomRuntime.renameRoom,
    onSelectModel: roomRuntime.setCodexModel,
    onCopyRoomMarkdown: workspaceFlow.copyRoomMarkdown,
    onCopySelectedMarkdown: workspaceFlow.copySelectedMessagesMarkdown,
    onToggleMarkdownSelection: toggleMarkdownSelectionMode,
    onClearSelectedMessages: clearSelectedMessages,
    onShareLocalPreview: roomRuntime.openLocalPreviewDialog,
    notices: roomInteraction.roomNotices,
    secretWarningVisible,
    onAcknowledgeSecretWarning: roomInteraction.acknowledgeRoomVisibilityWarning,
    markdownCopyFallback,
    copyMarkdownWithFallback: workspaceFlow.copyMarkdownWithFallback,
    setChatMessageForRoom,
    setMarkdownCopyFallbackForRoom,
    messages: selectedRuntime.chatMessageRows,
    approvalVisible: selectedRuntime.approvalVisible,
    approvalSummary: selectedRuntime.codexApprovalSummaryDisplay,
    codexRunning: selectedRuntime.codexRunning,
    roomCanUseChat: selectedRuntime.roomCanUseChat,
    draft,
    pendingAttachmentsForCount: pendingAttachments,
    pendingAttachments: selectedRuntime.pendingAttachmentRows,
    localPreviewCards: selectedRuntime.localPreviewCards,
    pendingAttachmentSummary: selectedRuntime.pendingAttachmentSummary,
    onToggleMessageSelection: toggleMessageSelection,
    onRemovePendingAttachment: workspaceFlow.removePendingAttachment,
    onSendMessage: roomRuntime.sendMessage,
    roomChatPanelActions: roomPanels.roomChatPanelActions
    },
    roomInspectorPanel: {
    activeTab: inspectorTab,
    activeBrowserUrl,
    browserUrl,
    canHostBrowser: roomInteraction.canHostBrowser,
    onBrowserUrlChange: (url) => setBrowserUrlForRoom(selectedRoom.id, url),
    onOpenBrowserNow: roomRuntime.openRoomBrowserNow,
    selectedRoom,
    projectPathDraft,
    gitStatus,
    hasSelectedRoom,
    isSelectedRoomLocked: roomInteraction.isSelectedRoomLocked,
    settingsBusy: selectedRuntime.settingsBusy,
    isActiveHost: roomInteraction.isActiveHost,
    defaultProjectPath,
    onProjectPathDraftChange: (path) => setProjectPathDraftForRoom(selectedRoom.id, path),
    onChooseProjectPath: roomRuntime.chooseProjectPath,
    onUpdateProjectPath: roomRuntime.updateProjectPath,
    teamRoster: {
      members: selectedTeamMemberRows,
      hasSelectedTeam: Boolean(workspaceState.selectedTeam),
      busy: selectedTeamMembersBusy,
      message: selectedTeamMembersMessage,
      onPromote: (member) => workspaceFlow.changeTeamMemberRole(member, "admin"),
      onDemote: (member) => workspaceFlow.changeTeamMemberRole(member, "member"),
      onTransferOwnership: workspaceFlow.transferOwnershipToTeamMember,
      onRemove: workspaceFlow.removeMemberFromTeam
    },
    roomMembers: {
      members: roomInteraction.roomMemberRows,
      localDeviceId: localIdentity.deviceId,
      message: appRuntimeState.deviceIdentityMessage,
      onCopyFingerprint: (member) => workspaceFlow.copyRoomMemberDeviceFingerprint(member, member.trusted),
      onTrust: workspaceFlow.trustRoomMemberDevice,
      onUntrust: workspaceFlow.untrustRoomMemberDevice
    },
    hostHandoffs: selectedRuntime.hostHandoffs,
    hostBusy: selectedRuntime.hostBusy,
    onAcceptHandoff: hostHandoffActions.acceptHostHandoff,
    encryptedInvite: {
      inviteApprovalGate,
      copyDisabled: !roomInteraction.canCopyRoomInvite,
      inviteSecretInput: invitePanelState.inviteSecretInput,
      inviteRequests: selectedRuntime.inviteRequests,
      localDeviceId: localIdentity.deviceId,
      gateDisabled: !hasSelectedRoom || roomInteraction.isSelectedRoomLocked,
      importDisabled: !invitePanelState.inviteSecretInput.trim(),
      rotateDisabled:
        !hasSelectedRoom ||
        roomInteraction.isSelectedRoomLocked ||
        !roomInteraction.isActiveHost ||
        selectedRuntime.keyRotationBusy,
      approvalDisabled:
        !hasSelectedRoom || roomInteraction.isSelectedRoomLocked || !roomInteraction.isActiveHost,
      keyRotationBusy: selectedRuntime.keyRotationBusy,
      inviteLink,
      inviteMessage,
      onCopyInvite: inviteActions.copyInviteLink,
      onInviteApprovalGateChange: (enabled) => setInviteApprovalGateForRoom(selectedRoom.id, enabled),
      onInviteSecretInputChange: invitePanelState.setInviteSecretInput,
      onImportInvite: inviteActions.joinInviteSecret,
      onRotateRoomKey: inviteActions.rotateSelectedRoomKey,
      onDecideInviteRequest: inviteActions.decideInviteJoinRequest
    },
    approvalPolicy: {
      labels: approvalPolicyLabels,
      message: settingsMessage,
      onSelectPolicy: roomRuntime.setApprovalPolicy
    },
    roomMode: {
      labels: roomModeLabels,
      onToggleMode: roomRuntime.toggleRoomMode
    },
    selectedCodexModel,
    customCodexModel,
    model: {
      customModel: customCodexModel,
      modelOptions: codexModelOptions,
      onSelectModel: roomRuntime.setCodexModel,
      onCustomModelChange: (model) => setCustomCodexModelForRoom(selectedRoom.id, model),
      onApplyCustomModel: () => roomRuntime.setCodexModel(customCodexModel)
    },
    localHistory: {
      historySettings: historyDefaultsState.historySettings,
      teamHistorySettings: historyDefaultsState.teamHistorySettings,
      selectedTeam: Boolean(workspaceState.selectedTeam),
      hasSelectedRoom,
      settingsBusy: selectedRuntime.settingsBusy,
      teamDefaultApprovalPolicy: historyDefaultsState.teamDefaultApprovalPolicy,
      approvalPolicyLabels,
      teamDefaultCodexModel: historyDefaultsState.teamDefaultCodexModel,
      defaultCodexModel,
      codexModelOptions,
      teamDefaultBrowserProfilePersistent: historyDefaultsState.teamDefaultBrowserProfilePersistent,
      teamDefaultInviteApprovalGate: historyDefaultsState.teamDefaultInviteApprovalGate,
      message: visibleHistoryMessage,
      onHistoryEnabledChange: (enabled) =>
        workspaceFlow.updateLocalHistorySettings({
          ...historyDefaultsState.historySettings,
          enabled
        }),
      onHistoryRetentionDaysChange: (retentionDays) =>
        workspaceFlow.updateLocalHistorySettings({
          ...historyDefaultsState.historySettings,
          retentionDays
        }),
      onClearRoomHistory: workspaceFlow.clearRoomHistory,
      onForgetRoomLocalData: workspaceFlow.forgetSelectedRoomLocalData,
      onApplyTeamDefaultsToRoom: workspaceFlow.applyTeamDefaultsToRoom,
      onTeamHistoryEnabledChange: (enabled) =>
        workspaceFlow.updateTeamHistoryDefaults({
          ...historyDefaultsState.teamHistorySettings,
          enabled
        }),
      onTeamHistoryRetentionDaysChange: (retentionDays) =>
        workspaceFlow.updateTeamHistoryDefaults({
          ...historyDefaultsState.teamHistorySettings,
          retentionDays
        }),
      onTeamDefaultApprovalPolicyChange: workspaceFlow.updateTeamDefaultApprovalPolicy,
      onTeamDefaultCodexModelChange: workspaceFlow.updateTeamDefaultCodexModel,
      onTeamDefaultBrowserProfilePersistentChange: historyDefaultsState.setTeamDefaultBrowserProfilePersistent,
      onTeamDefaultInviteApprovalGateChange: workspaceFlow.updateTeamDefaultInviteApprovalGate
    },
    workspaceFiles: {
      fileQuery,
      projectFiles,
      selectedFile,
      selectedDiff,
      fileBusy,
      fileMessage,
      canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
      selectedFileRisks: roomDisplay.selectedFileRisks,
      selectedFileNeedsAttachmentReview: roomDisplay.selectedFileNeedsAttachmentReview,
      selectedSensitiveFileReviewed: roomDisplay.selectedSensitiveFileReviewed,
      selectedAttachmentActionLabel: roomDisplay.selectedAttachmentReview?.actionLabel ?? "Attach",
      selectedAttachmentWarningDetail: roomDisplay.selectedAttachmentReview?.warningDetail ?? undefined,
      filePreviewTab,
      ...roomPanels.workspaceFilesPanelActions
    },
    gitHandoff: {
      draft: gitWorkflowDraft,
      preview: roomInteraction.gitApprovalPreview,
      readiness: roomInteraction.githubWorkflowReadiness,
      canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
      gitWorkflowBusy,
      isActiveHost: roomInteraction.isActiveHost,
      message: gitWorkflowMessage,
      onDraftChange: updateSelectedGitWorkflowDraft,
      onCopyPullRequestDraftMarkdown: workspaceFlow.copyPullRequestDraftMarkdown,
      onApproveGitWorkflow: roomRuntime.approveGitWorkflow
    },
    githubActions: {
      summary: roomInteraction.actionsSummary,
      readiness: roomInteraction.githubActionsReadiness,
      runs: actionRuns,
      owner: gitWorkflowDraft.prOwner,
      repo: gitWorkflowDraft.prRepo,
      branch: gitWorkflowDraft.branchName,
      lastChecked: actionsLastChecked,
      busy: actionsBusy,
      refreshDisabled:
        !roomInteraction.canReadLocalWorkspace ||
        actionsBusy ||
        !roomInteraction.isActiveHost ||
        !roomInteraction.githubActionsReadiness.ready,
      currentUserSignedIn: Boolean(githubAuth.currentUser),
      message: actionsMessage,
      onRefresh: () => roomRuntime.refreshGitHubActions()
    },
    terminal: {
      terminalName,
      terminalCommand,
      terminalInput,
      terminalBusy,
      terminalError,
      terminalCommandRisks: roomDisplay.terminalCommandRisks,
      terminalRisks: roomDisplay.terminalRisks,
      codexEvents: roomDisplay.codexEventRows,
      commandRequests: roomDisplay.terminalRequestRows,
      roomTerminals,
      selectedTerminal: selectedRuntime.selectedTerminal,
      selectedTerminalId,
      selectedTerminalCanControl: selectedRuntime.selectedTerminalCanControl,
      selectedTerminalCanRestart: selectedRuntime.selectedTerminalCanRestart,
      terminalOutputLines: roomDisplay.terminalOutputLines,
      codexRunning: selectedRuntime.codexRunning,
      canReadLocalWorkspace: roomInteraction.canReadLocalWorkspace,
      canRequestWorkspace: roomInteraction.canRequestWorkspace,
      ...roomPanels.terminalPanelActions
    }
    },
    appSidebar: {
    currentUser: githubAuth.currentUser,
    authBusy: githubAuth.authBusy,
    authConfig: githubAuth.authConfig,
    authError: githubAuth.authError,
    deviceFlow: githubAuth.deviceFlow,
    sidebarQuery: workspaceState.sidebarQuery,
    searchActive: roomDisplay.searchActive,
    workspaceError: workspaceState.workspaceError,
    newTeamName: workspaceState.newTeamName,
    newRoomName: workspaceState.newRoomName,
    newRoomProjectPath: workspaceState.newRoomProjectPath,
    selectedTeamId: workspaceState.selectedTeam,
    teams: roomDisplay.sidebarTeamRows,
    rooms: roomDisplay.sidebarRoomRows,
    messageHits: roomDisplay.sidebarMessageHitRows,
    historySearchBusy: appRuntimeState.historySearchBusy,
    activeSidebarPanel: workspaceState.activeSidebarPanel,
    themeMode: theme.themeMode,
    localUserName: localIdentity.localUser.name,
    selectedRoomName: selectedRoom.name,
    deviceId: localIdentity.deviceId,
    deviceIdentity: appRuntimeState.deviceIdentity,
    deviceIdentityMessage: appRuntimeState.deviceIdentityMessage,
    relayStatus: appRuntimeState.relayStatus,
    relayWsUrl: appConfigState.appConfig.relayWsUrl,
    relayHttpUrl: appConfigState.appConfig.relayHttpUrl,
    codexProbe: appRuntimeState.codexProbe,
    projectPath: selectedRoom.projectPath,
    selectedCodexModel,
    selectedRoomApprovalPolicy: selectedRoom.approvalPolicy,
    roomPosture: roomInteraction.roomPosture,
    hasSelectedRoom,
    isSelectedRoomLocked: roomInteraction.isSelectedRoomLocked,
    settingsBusy: selectedRuntime.settingsBusy,
    isActiveHost: roomInteraction.isActiveHost,
    relayHttpDraft: appConfigState.relayHttpDraft,
    relayWsDraft: appConfigState.relayWsDraft,
    selectedRoomMode: selectedRoom.mode,
    roomSettingsGateMessage: roomInteraction.roomSettingsGateMessage,
    historySettings: historyDefaultsState.historySettings,
    teamHistorySettings: historyDefaultsState.teamHistorySettings,
    teamDefaultApprovalPolicy: historyDefaultsState.teamDefaultApprovalPolicy,
    teamDefaultCodexModel: historyDefaultsState.teamDefaultCodexModel,
    teamDefaultBrowserProfilePersistent: historyDefaultsState.teamDefaultBrowserProfilePersistent,
    teamDefaultInviteApprovalGate: historyDefaultsState.teamDefaultInviteApprovalGate,
    appConfigMessage: appConfigState.appConfigMessage,
    roomSettingsMessage: settingsMessage,
    historyMessage: visibleHistoryMessage,
    onSignIn: githubAuth.beginGitHubSignIn,
    onSignOut: roomRuntime.signOut,
    onSidebarQueryChange: workspaceState.setSidebarQuery,
    onNewTeamNameChange: workspaceState.setNewTeamName,
    onCreateTeam: workspaceFlow.addTeam,
    onSelectTeam: workspaceState.setSelectedTeam,
    onNewRoomNameChange: workspaceState.setNewRoomName,
    onNewRoomProjectPathChange: workspaceState.setNewRoomProjectPath,
    onChooseNewRoomProjectPath: workspaceFlow.chooseNewRoomProjectPath,
    onCreateRoom: workspaceFlow.addRoom,
    onSelectRoom: workspaceState.setSelectedRoomId,
    onSelectSidebarPanel: workspaceState.setActiveSidebarPanel,
    onToggleTheme: theme.toggleThemeMode,
    onRotateDeviceIdentity: roomRuntime.rotateDeviceIdentity,
    onChooseProject: roomRuntime.chooseProjectPath,
    onRelayHttpDraftChange: appConfigState.setRelayHttpDraft,
    onRelayWsDraftChange: appConfigState.setRelayWsDraft,
    onResetRelay: appConfigState.resetRelayConfiguration,
    onSaveRelay: appConfigState.saveRelayConfiguration,
    onToggleRoomMode: roomRuntime.toggleRoomMode,
    onHistorySettingsChange: workspaceFlow.updateLocalHistorySettings,
    onClearRoomHistory: workspaceFlow.clearRoomHistory,
    onForgetRoomLocalData: workspaceFlow.forgetSelectedRoomLocalData,
    onTeamHistoryDefaultsChange: workspaceFlow.updateTeamHistoryDefaults,
    onTeamDefaultApprovalPolicyChange: workspaceFlow.updateTeamDefaultApprovalPolicy,
    onTeamDefaultCodexModelChange: workspaceFlow.updateTeamDefaultCodexModel,
    onTeamDefaultBrowserProfilePersistentChange: historyDefaultsState.setTeamDefaultBrowserProfilePersistent,
    onTeamDefaultInviteApprovalGateChange: workspaceFlow.updateTeamDefaultInviteApprovalGate,
    onApplyTeamDefaultsToRoom: workspaceFlow.applyTeamDefaultsToRoom,
    roomRecords: workspaceState.rooms
    },
    localPreviewDialog: {
    localPreviewDialog: localPreviewState.localPreviewDialog,
    setLocalPreviewDialog: localPreviewState.setLocalPreviewDialog,
    localPreviewBusy: selectedRuntime.localPreviewBusy,
    prepareLocalPreviewConfirmation: roomRuntime.prepareLocalPreviewConfirmation,
    confirmLocalPreviewShare: roomRuntime.confirmLocalPreviewShare
    }
  });

  return <AppShellView {...appView.appShellViewProps} />;
}
